### ISSUE TITLE
Query underlying data size (column data and number of rows)

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#100]
Hey, I'd like to be able to query the number of rows in the underlying data table, currently the DataTable returned by getUnderlyingDataAsync contains a totalRowCount but that is limited by the number of rows actually returned. I dont care about the actual individual rows in the data and therefore set maxRows to 1 but i get a totalRowCount of 1 instead of the actual size of the underlying data.

Aditionally if maxRows is not set Datasource.getUnderlyingDataAsync will return a totalRowCount of 10.000 instead of returning the actual row count of the underlying data.

Perhaps the upcomming pagination feature will allow me to set pageSize of 1 and report the correct totalRowCount but this is currently unclear as the feature is not yet implemented.

**Comment by Kovner** [comment]
Yeah this is a reasonable request. I'll put it on our backlog, but I doubt it will be in v1.
