### ISSUE TITLE
[bug] error opening a dashboard containing an extension using the configure context menu item option

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#101]
When saving and then opening a dashboard containing an extesion that has the configure context menu item i encounter an error:

```
Unable to complete action
Errors occurred while trying to load the workbook "C:\Users\tjalling\Downloads\test\test.twb". The load was not able to complete successfully.
Error Code: 
Errors occurred while trying to load the workbook "C:\Users\tjalling\Downloads\test\test.twb". The load was not able to complete successfully.
Error(58115,81): value 'configure' has length '9' which exceeds maxLength facet value '0' (id: C:\Users\tjalling\Downloads\test\test.twb)

```

The `configure` value the error seems to be referring to in the .twb looks like this:
(This is inside the `<referenced-extension>` tag)
```xml 
<context-menu>
  <configure-context-menu-item>configure</configure-context-menu-item>
</context-menu>
```

This same value in my .trex file looks like this:
```xml
<context-menu>
  <configure-context-menu-item />
</context-menu>
```

When saving the workbook it seems its "unfolding" this element and giving it the content `configure` but when reading it expects the element to be empty.

When i manually change the .twb context menu element to `<configure-context-menu-item />` the workbook opens fine but the extension seems to have lost its permissions as it will not show anything (not even the "Eextension was denied the required permissions" warning) until i select `Reset Permissions` from the context menu.

**Comment by Kovner** [comment]
Thanks for pointing this out. We have a fix checked in. It _may_ be in the build we release later this week, but that depends on a few things. If not, it will be in the next build after that.
