### ISSUE TITLE
How do change server ipaddress & port

### ISSUE THREAD

**Issue by pallaviMN** [tableau/extensions-api#102]
Whenever i run npm start, it always runs on localhost with 8765 port. How can i change this?

**Comment by pallaviMN** [comment]
Can we run npm start & tabeau server on the same port

**Comment by pallaviMN** [comment]
I am running server on localhost://8000 & extension api  npm start on localhost://8765.

 Here when i tried to change tableau server port to 8765, it doesnt wok as npm is already running in that port.

 Now when i publish my workbook, it will have URL starting with localhost://8000, so in extension javascript file , when i want to access window.location.URL it gives me "localhost://8765/....." but i need the published tableau URL. 

If i try to access via window.parent.location.href it gives error

**Comment by pallaviMN** [comment]
Uncaught DOMException: Blocked a frame with origin "http://localhost:8765" from accessing a cross-origin frame

**Comment by Kovner** [comment]
You can modify the package.json to change what command is run when you type 'npm start'

**Comment by pallaviMN** [comment]
will it avoid cross origin error? but in package.json there is no way to change to the port to 8000

**Comment by pallaviMN** [comment]
i have changed the 8765 in package.json to 8000

**Comment by pallaviMN** [comment]
Error: listen EADDRINUSE 0.0.0.0:8000

getting this error as tableau server running on this

**Comment by Kovner** [comment]
That means you have another application running on that port. It seems like you already have Server running on 8000, so you won't be able to run the web app on port 8000 too.

**Comment by Kovner** [comment]
If you're just trying to have them on the same port to avoid that cross-origin error, then that won't work. You can't get the url of the parent url . That would have to be something we add to the API. Can you explain why you need the url of the dashboard?

**Comment by pallaviMN** [comment]
if the ports are different, then when i access parent.location.href in webapp, then it gives error saying that its an cross origin requests

**Comment by pallaviMN** [comment]
1) Tableau server running on localhost://8000
2) Extension API running on localhost://8765

Now in the default "filtering.js" file we are capturing & displaying all filtered results. 
This filtered results along with the pubslished dashboard URL, we have pass to some ajax request. 
but , tableau dashboard URL is created with "localhost://8000". Now in filtering.js, when i try to fetch window.location.href it gives me URL of "filtering.html" loaded in iframe but i want parent location. When i write console.log(parent.location.href) it gives me cross origin error.

**Comment by pallaviMN** [comment]
or is there any option to enable cors in the node modules?

**Comment by pallaviMN** [comment]
yes exactly, you got me right. 
I need that URL because we create an simple "export" button in the extension object. On clicking that button , i need to capture the dashboard URL & make an ajax call to our another web server. In that web server, we have already have stored this dashboard URL in the DB. So ajax request sent by us from extension object, need to include dashboard URL for our web server to do some process.

**Comment by pallaviMN** [comment]
so thinking can we enable cors in the node modules of extension object. If yes, then please tell me how can we achieve it?

**Comment by KeshiaRose** [comment]
Hi pallaviMN,

You can use `document.referrer` to get the URL of a published workbook. This will avoid the CORS issue. More info in this [post](https://humanwhocodes.com/blog/2013/04/16/getting-the-url-of-an-iframes-parent/).
