### ISSUE TITLE
"click to show all values" on range filter breaks applyRangeFilterAsync

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#105]
After clicking this button:
![capture](https://user-images.githubusercontent.com/5736783/38681425-ef8a6580-3e68-11e8-9bd3-eb1439d404a5.PNG)
`Worksheet.applyRangeFilterAsync` stops being able to update the filter until the filter is changed manually in Tableau.

**Comment by Kovner** [comment]
Tjallng, you're my hero for finding all these bugs this week!

I've logged this internally. Thanks!

**Comment by tjallingt** [comment]
And you are my hero for responding to all my issues so extremely quickly. 

Btw i wanted to respond to your other messages but our timezones are quite out of sync so i completely forgot ;d

**Comment by johnDance** [comment]
This has been fixed. It should be released in 2019.1. Thanks for the bug report!
