### ISSUE TITLE
Followed your steps to install tableau extensions...

### ISSUE THREAD

**Issue by cnbala** [tableau/extensions-api#118]
Followed your steps to install tableau extensions.But I am not able to see the extensions option in tableau server.

Steps Followed:
1.Download extensions-api-master zip folder from github. Install Node.js and npm 
2.Copy the Parameters .trex files of the sample you wish to run to ~\Documents\My Tableau Repository (Beta)\Extensions so they are available to Tableau.
3.Open a command prompt window to the location where you cloned this repo.
4.Run npm install.
5.Run npm start

I am using Tableau desktop Professional Version 2018.1.0.
Please help me resolve the issue ASAP as I am new to using extension API.

**Comment by d45** [comment]
Did you download Tableau Desktop and Tableau Server from the [Extensions API Developer Preview](https://prerelease.tableau.com/project/home.html?cap=52e2710a0793434d82142736c7ab3029)?   
You need to be running a version of Tableau Desktop or Tableau Server that supports the Extensions API.  
You can also use the Tableau 2018.2 beta release (preferred). The beta is available from the [Tableau 2018.2 Beta](https://prerelease.tableau.com/project/home.html?cap=c43269484c1f45a68f5ad4fc4660b2ab) site.

**Comment by dlpate2525** [comment]
Hello, 
Some large enterprise companies are on previous versions of Tableau due to the red tape around upgrades. Will compatibility for Extensions & TabPy come with 10.3 & 10.4 versions?

**Comment by KeshiaRose** [comment]
In order to use extensions, you will need to upgrade to at least 2018.2.
