### ISSUE TITLE
Mouse doesn't interact with select menu in configure screen

### ISSUE THREAD

**Issue by craigbloodworth** [tableau/extensions-api#124]
On a mac is anybody else finding that a standard select list can't be interacted with using the mouse pointer? Keyboard works but not the mouse pointer:
![image](https://user-images.githubusercontent.com/8116300/40809871-d8678a4a-6523-11e8-977f-18bb56760fec.png)

**Comment by Kovner** [comment]
Yes, this is a known issue and one that we believe we'll have a fix for before release.

**Comment by craigbloodworth** [comment]
@Kovner does it affect both Mac and Windows?
