### ISSUE TITLE
getActiveTablesAsync broke DataSource sample

### ISSUE THREAD

**Issue by xsgao-github** [tableau/extensions-api#129]
I dragged Samples\DataSources\Datasource.trex in a dashboard and load it up. It displayed data source correctly, but when I click on the info button, no modal dialog shows up. Using Chrome to debug, I found that Datasource.getActiveTablesAsync() is causing problems, neither success or reject function is called, or the line after getActiveTablesAsync() call.

Here is the snippet I was referring, from datasources.js:

    dataSource.getActiveTablesAsync().then(function (activeTables) {
      // Loop through each table that was used in creating this datasource
      let tableStr = '';
      activeTables.forEach(function (table) {
        tableStr += table.name + ', ';
      });

      // Slice of the last ", " for formatting.
      $('#activeTablesDetail').text(tableStr.slice(0, -2));
    }, function(error) {
      alert(error);
    });

I am using SuperStore sample .tds, and here is the error I got:

"k":"msg","v":"WebPage javaScriptConsoleMessage: message=Uncaught Error: unknown-verb-id: Unknown ApiVerb: get-active-tables sourceId=userscript:api-platform-js.js lineNumber=2298"}

**Comment by KeshiaRose** [comment]
Please try this with an official release of 2018.2 or higher and re-open if you are still having this issue.
