### ISSUE TITLE
get full datasource/database/schema/table/column information of field

### ISSUE THREAD

**Issue by xsgao-github** [tableau/extensions-api#130]
For each fields used in a worksheet, we would like to know where does this field come from, basically datasource connection, database/schema/table/column name.

Is there any API support this requirement?

**Comment by KeshiaRose** [comment]
Currently, the Extensions API will not give you insight at that level. If you are interested in seeing this information on Server, there is an API that is being worked on that will let you query data source information, but it will likely not be released until later this year.
