### ISSUE TITLE
Tutorial Issue

### ISSUE THREAD

**Issue by AvonBarks** [tableau/extensions-api#132]
When pulling up Part 01 for the Tutorial, I can't get it to display
"Hello from 'dashboardname'"

When adding other extensions from the samples, I am unable to load up all of the extension and usually have partially broken ones appear.

Can anybody help me with this?

Thanks!

**Comment by d45** [comment]
Sorry to hear that you are having problems with the tutorial and extensions. From what you describe it is hard to tell exactly what is going wrong. It could be a mismatch with the version of Tableau you are running, or a problem with the localhost web service.  I assume that you have downloaded or cloned the repo on your computer.

- Are you running the latest release of [Tableau 2018.2 from the beta site](https://prerelease.tableau.com/project/home.html?cap=c43269484c1f45a68f5ad4fc4660b2ab)?  
- What error messages do you see when you load the extensions in Tableau? 
- When you run the **npm install** and **npm start** to start the localhost server, do you see error messages about files not found, etc. in the command window? 

You could also try a couple of the hosted extensions from the Tableau 2018.2 beta site. Try the Clear Filters or Dynamic Parameter examples, from [Dashboard Extensions](https://prerelease.tableau.com/project/article/default.html?cap=c43269484c1f45a68f5ad4fc4660b2ab&arttypeid=741c8e27001e49d8a4d3194d4144b8b0). If you download the `.trex` files, you won't need to run a localhost web server.

**Comment by KeshiaRose** [comment]
Please let us know if you are still having trouble with the tutorial using an official release (2018.2 or higher). If so, please re-open and respond with the items Dave mentioned.
