### ISSUE TITLE
Resizing extension triggers a reload

### ISSUE THREAD

**Issue by elatt** [tableau/extensions-api#133]
I'm not sure if this is strictly a bug but we are finding the behavior to be not optimal from a experience perspective. The problem is that after you have dragged your extension into a dashboard, if you attempt to resize the extension, it triggers are full refresh of the page. It is also more confusing that if you have your dashboard size set to `Auto` and you resize the main Tableau window, the tiles inside the dashboard are allowed to shrink and grow but the extension does not perform a full refresh.

We find this behavior to be awkward for users and would prefer that resizing the extension in the dashboard was similar to simply resizing a browser window. Performing a full refresh for every resize is problematic because it causes us to have to make our network requests all over again and redraw the full page.

**Comment by Kovner** [comment]
Yep we have fixed this in recent builds. You shouldn't see the refresh in that situation once 2018.2 is released.
