### ISSUE TITLE
Dashboard extension appears blank when switching to presenter mode

### ISSUE THREAD

**Issue by elatt** [tableau/extensions-api#134]
This has been tested on 2018.2 Beta 1 for Mac

When you change from the normal Tableau view into Presenter mode, our dashboard extension gets _cleared out_ and appears empty until you click somewhere inside it. After you click, the extension displays again. Our dashboard is set to a fixed size (Generic Desktop). If you click then it seems to cause the extension to reload and then it displays.

**Comment by Kovner** [comment]
Apologies for being so slow to respond to this. We tried to reproduce this in 2018.2.10 and 2019.1 and didn't see the behavior you're describing. Can you let us know if you're still seeing this behavior?

**Comment by elatt** [comment]
I no longer have access to Tableau and have moved on.
