### ISSUE TITLE
removeEventListener always returns false & doesn't remove event listener

### ISSUE THREAD

**Issue by craigbloodworth** [tableau/extensions-api#137]
The function `sheet.removeEventListener()` always returns false even when an event listener exists on the sheet and doesn't remove the listener:
![image](https://user-images.githubusercontent.com/8116300/42508164-718e81f8-843f-11e8-9e93-f0cd599871d7.png)
The only way to remove the listener is to manually edit the _handlers array in _eventListenerManagers:
`sheet._eventListenerManagers["filter-changed"]._handlers = [];`

**Comment by johnDance** [comment]
Hi Craig:
For removeEventListener to succeed, you need to pass the same TableauEventHandlerFn that you registered with addEventListener. If you pass in a different event handler, or pass in no event handler, or registered a lambda function, then removeEventListener will return false.

For example, the following works:
worksheet.addEventListener(tableau.TableauEventType.MarkSelectionChanged, logSelectionEvent);
worksheet.removeEventListener(tableau.TableauEventType.MarkSelectionChanged, logSelectionEvent);

Hopefully this helps.
Thanks,
John
