### ISSUE TITLE
Request - Typings

### ISSUE THREAD

**Issue by kostenickj** [tableau/extensions-api#139]
We are using Typescript to develop some extensions, could you provide Typings? It would certainly make it easier to use.

**Comment by pavloko** [comment]
This certainly would help as well. It seems like you're using typescript to develop the SDK anyways.

**Comment by mfioravanti-yseop** [comment]
Hello,
We would also need the typings, to work with typescript. Besides, it seems, reading the documentation, that they already exist, for example:
Defined in Namespaces/Extensions.ts:60

Please help us :-)

**Comment by rcollette** [comment]
You'll find that your source code for this API library is smaller, and easier to maintain if you convert it to Typescript.   You will get ES6 compatible modules (that can still be webpacked) and type definitions will be available for the generated javascript, which then provides excellent code assistance.

You'll also be able to use es6 features like async/await even if you are still targeting es5 compatibility.

**Comment by johnDance** [comment]
Good news!
We are starting to work on Typescript bindings as I type this message.
John

**Comment by rcollette** [comment]
I forked this project and added a DataSources-Typescript example which is a conversion of that sample to Typescript, targeting ES2017 and updating the code to use those features such as classes, async/await, arrow functions, etc.  

It also uses TSLint which provides some additional guidance (usage of let vs. const).  Added a .editorconfig and prettierconfig.json

If of any interest I can create a PR and further comments about needed modifications can be made on that.

https://github.com/rcollette/extensions-api

**Comment by ashwinar** [comment]
We are happy to announce as of today, we released Extensions API 1.3, which includes type definitions library for Extensions API. Release notes here:
https://tableau.github.io/extensions-api/docs/trex_release-notes.html#extensions-api-library-v13
