### ISSUE TITLE
Tableau Public is looping

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#141]
When publishing a workbook with extension to Tableau Public some kind of looping occurs. The dashboard goes crazy and crashes. Example: https://public.tableau.com/profile/leonardo.sampieri#!/vizhome/sankeytestA/Dashboard3

**Comment by johnDance** [comment]
Hello!
Thank you for your report. I have good news and bad news. The good news is that we have found the issue, and will be working to resolve it. Somehow the user is not allowed to get the summary data for this workbook. The browser is getting a 403 error response from the server, and then reloading the page. We will fix that.

The bad news is that we have decided that it is best to disable extensions on public for a while while we get some monitoring tools in place.

Thanks again for your report. We will work to fix the underlying issue.
John
