### ISSUE TITLE
Column class should contain FieldRole property 

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#142]
[Columns](https://tableau.github.io/extensions-api/docs/interfaces/column.html) currently don't give information about the field role.

This makes it difficult to distinguish between dimensions and measures in an extension that is using `worksheet.getSummaryDataAsync` without doing a lot of work figuring out which columns relates to what [Field](https://tableau.github.io/extensions-api/docs/interfaces/field.html) returned by `worksheet.getDataSourcesAsync`.

The easier way to derive whether a column is a dimension or a measure is by matching it against a regex like this: `/^(AGG|SUM|MIN|MAX|AVG|MED|CNT|STD)(?=\()/` however this breaks down when the language is not set to English (`SUMA()` or even `总和()`).

The reason I'd like to be able to distinguish between roles and measures in the DataTable returned by `getSummaryDataAsync` is that in a few extensions I allow users to configure the extension by picking columns that will be used to provide the extension with data. I don't want to overload the user with a gigantic list of columns if i already know only dimensions/measures make sense for that specific selection.

If this is not possible/undesireable then i'd like to know so i can update my extensions.

**Comment by merlijnbuit** [comment]
Hi Tableua,

We really need an ID prop on a column.
We are keep getting this message from several big Tableau users around the world.

The workbook is being created in English, whenever a user across the world uses this dashboard on Tableau Server with a different language it crashes because SUM is no longer part of the fieldName.

**Comment by johnDance** [comment]
Hi Merlijn:
I'm going to see if I can include this in the summary data improvements that we are making.
John

**Comment by demartsc** [comment]
Not much to add here other than this would be a huge value add. Reliance on the field names can be very troublesome and referencing an ID instead would solve a lot of potential bugs like the one described above. So basically I am just commenting to upvote :)

**Comment by johnDance** [comment]
upvote noted. :-)
