### ISSUE TITLE
when I open add extension(example,datasource),the name does not appear.always "loading",what do happen error?

### ISSUE THREAD

**Issue by aiwenForGit** [tableau/extensions-api#145]
I frist use tableau extension.when I open add extension(example,datasource)
![image](https://user-images.githubusercontent.com/241340/44083721-627de35c-9fe7-11e8-862d-2f4e16e0f38c.png),the name does not appear.always "loading",what do happen error?

**Comment by aiwenForGit** [comment]
somebody help me!!!

**Comment by d45** [comment]
There might be a mismatch with the version of the extensions library you are using.  Are you using the latest version of the Tableau (2018.2)? Is the extension using the latest version of the the library (tableau-extensions-1.0.0.js)?  If not, you might want to re-download the project from the GitHub repository. 

It might help if you can check for errors using the Chromium debugger. See [Remote Debugging of JavaScript and HTML](https://tableau.github.io/extensions-api/docs/trex_debugging.html).

**Comment by aiwenForGit** [comment]
![image](https://user-images.githubusercontent.com/241340/44191026-fdfb4980-a15b-11e8-9b5b-13cc0a5986c7.png)

I redownload it.but error again.

**Comment by d45** [comment]
Are you having trouble with every sample dashboard extension on GitHub (including the tutorial)?  That is, all of the samples that you run on your computer as localhost? (`npm start`)?  Still looks like there is a version mismatch issue. 

Are you running the released version of [Tablelau 2018.2](https://www.tableau.com/support/releases)? 

You might also try running some of the extensions from the [Extensions Gallery](https://extensiongallery.tableau.com/) to see if dashboard extensions can run correctly when there aren't any local dependencies.

**Comment by KeshiaRose** [comment]
Please try with an official release (2018.2 or higher) and re-open if you are still experiencing this issue.
