### ISSUE TITLE
UINamespace Example

### ISSUE THREAD

**Issue by sretmos** [tableau/extensions-api#150]
I am trying to use the UINamespace example on my Tableau Server. I select the data source to refresh, set the time interval, and then save the dashboard when I am in Edit mode. I close out of "Edit" mode, but when I go back to "View" mode, it hasn't saved my changes. The frame for the extension continues to show "Configure extension to proceed".  Is there another setting I need to configure on Tableau Server in order for it to save the changes from the pop-up dialog window?
![configureextension](https://user-images.githubusercontent.com/18900120/44608396-28cb4a80-a7b9-11e8-8a1e-cfc79a3349d8.png)

**Comment by Kovner** [comment]
We haven't seen this and will investigate: You're doing the adding of the Extension and configuration in web authoring?

**Comment by sretmos** [comment]
yes, this is through the browser.

**Comment by sretmos** [comment]
i haven't fixed it.
