### ISSUE TITLE
Dropdowns still not working on Mac OSX

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#163]
Hi,

It looks like normal HTML select dropdowns are still not working on Mac OSX.
Are you guys aware of this? 

Merlijn

**Comment by afreeland** [comment]
I am using macOS and Tableau 2018.2 and here is a snippet of an extension that I modified real quick to test.
![image](https://user-images.githubusercontent.com/3135030/47025047-d3644780-d130-11e8-8706-baae29b915b9.png)

I have seen where if you use a library that is meant to pretty up select elements that they will often default the `select` to `display:none` and it wouldnt be visible.  Does it render in Chrome outside of Tableau?

**Comment by johnDance** [comment]
Hello Merlijn:
This has been fixed internally. Unfortunately, it won't appear until 2019.1. Meanwhile, if it is any consolation, you can use your keyboard to navigate and select.
John
