### ISSUE TITLE
Idea: Drag and Drop extension on dashboard

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#168]
How achievable would something like this be?

![drag_and_drop_extensions](https://user-images.githubusercontent.com/16118919/47779733-1f4ee900-dcfa-11e8-8885-980653f0651a.gif)

The same counts for images and webpage urls and other dashboard elements.

**Comment by johnDance** [comment]
Great idea. I have forwarded this to the dashboard team, which would own this feature.

**Comment by johnDance** [comment]
The need to support dragging a .trex has essentially been obviated by the in product exchange.
