### ISSUE TITLE
[suggestion] Column.formatValue(value): string formattedValue

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#172]
Would be handy if we could ask Tableau to format a value the same way it would be displayed inside Tableau. For example when requesting summary data and doing some calculations with [DataValue](https://tableau.github.io/extensions-api/docs/interfaces/datavalue.html).value.

```javascript
// collect some ingredients
let { columns: [firstCol], data: rows } = await datasheet.getSummaryDataAsync();

// quick mathz
let sum = 0;
for (let row of rows) {
  sum += row[firstCol.index].value;
}

// format sum for display
let formattedSum = firstCol.formatValue(sum);
```

Could also be part of [Field](https://tableau.github.io/extensions-api/docs/interfaces/field.html), not sure what is better for you but I'm usually working with columns (and not really touching the Datasource stuff) so I'd prefer it on the [Column](https://tableau.github.io/extensions-api/docs/interfaces/column.html).

If the formatting happens inside Tableau it would probably need to be `formatValueAsync` but since if this API where to be implemented I'd guess it wouldn't be strange for it to be called in a loop and i think implementing it client-side would be more performant. 

In any case it would be nice to know what the format string looks like even if we can't get a function that will format the value for us.

**Comment by chris-lehman** [comment]
Any update on adding this feature to the API? I'm struggling with date types fields in my workbook returned as strings formatted like 2017.00, 2018.00, 2019.00, etc, from getSummaryDataAsync. Is there something simple I'm missing here in terms of making sure data returned from the API is formatted like it is in Tableau?

**Comment by Kovner** [comment]
@chris-lehman We do now have .formattedValue that should give you what you need. If that's missing any options or formatting that you need, let us know.

**Comment by chris-lehman** [comment]
Thanks @Kovner. I did end up using formattedValue along with a trick I found online to add a "selectAll" calculated field with a value of 1 to select all of the marks for any sheet. So glad that works!
