### ISSUE TITLE
Bug when reloading remote debugging session

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#173]
Hi guys,

We are facing an issue with the remote debugging console. Somehow it remembers something of the previous session when you hit F5. The reason why we use F5 instead of the Reload button in the extensions is because the Reload button destroys everything and I have to log in to my 'secret extension'  application again.

Example: (me spraying F5 in Chromium)
![f5_refresh](https://user-images.githubusercontent.com/16118919/48701303-74da2f80-ebee-11e8-9d0e-e9d2081e43e2.gif)

Hitting the reload button in Chomium doesn't duplicate it, but also stills shows my current console which make me think nothing really gets reloaded.

Here is my sample code. This appears to work with all event listeners.
```js
tableau.extensions.initializeAsync({ configure: function() {} }).then(function() {
  var dashboard = tableau.extensions.dashboardContent.dashboard;
  dashboard.worksheets[0].addEventListener('mark-selection-changed', function(event) {
    console.log(event);
  });
});
```

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
