### ISSUE TITLE
tableau extension - getFilter/sAsync call returns error on real dashboards

### ISSUE THREAD

**Issue by ArunSanthosh** [tableau/extensions-api#184]
tableau extension - getFilter/sAsync call returns Error:internal-error:Enum mapping not found for:undefined

I used the concepts in Filtering sample to monitor the state of several filters in a dashboard
and set value of a parameter based on the selections made by user for these filters.
On changing the value in any of the monitored filters, the filter change handler function gets triggered correctly. The subsequent logic gets the filter states, sets the parameter as expected and everything works as expected as long as the dashboard has limited content. 

Once I load additional worksheets on there, desktop takes more time to run all the queries and starts bringing up the 'Computing visualization..' dialog after changes to filter values. Then, the call to either getFilterAsync (to get value of the specific filter) or getFiltersAsync (to get value of all sheet filters) from the filter change event handler function results in 'Error:internal-error:Enum mapping not found for:undefined' if the 'Computing visualization...' dialog box is still present. Tableau desktop also throws 'Unable to complete action' error box at this point.
(I haven't been able to test this on tableau server yet)

I tried putting the function on 10 second delay to give desktop the time to fetch data & close the 'Computing...' screen. This works as long as desktop is done in that 10s time. Also tried putting the function in a recursive time wait loop (for max of 10 calls) on hitting error. This also works as long as I close the 'Unable to complete action' pop ups. 
However, both these workarounds are not satisfactory as it stands in way of getting a refreshed screen to user in the minimum amount of time.

Raised this issue in tableau support site; was told that tableau supports only the standard examples and that issues with custom usage should be raised on github. Ahead of posting here, I also tried with the standard filtering sample provided with the extensions bundle. Same issue exists there too. It works as long as the dashboard has minimal content. On any busy dashboard with more sheets and filters, the standard sample also hits the same issue. (Have replied on my original case with this info as well)

Something's got to change - Either these APIs should be able to work regardless of the state of tableau desktop or the triggering of the filter change handler function should be delayed till desktop is able to handle subsequent actions.

Please address at the earliest as this is a major blocker in using the power of tableau extensions. Thanks.

Regards,
Arun Santhosh

**Comment by ArunSanthosh** [comment]
Hi John,

Appreciate the quick response.
Absolutely! You just made my day!

I'm in process of getting my scripts whitelisted by server admins 
and have several corporate hurdles to tackle for the same.
Hope to test this out on server by next week.
Meanwhile, with your positive response, I can now ignore this error and proceed with further customization on desktop.
Thanks again..

I will watch for further updates so that I can pull latest extensions js / desktop version with the fix once available.

Regards,
Arun Santhosh

**Comment by johnDance** [comment]
Hi Arun:
We have fixed the desktop issue with complicated dashboards. It will be part of 2019.1.
Thanks again for your report.
John
