### ISSUE TITLE
getSelectedMarksAsync is not responding to dual axis chart

### ISSUE THREAD

**Issue by dsjijo** [tableau/extensions-api#185]
I have a stacked barchart+ line chart as a dual axis like below
![image](https://user-images.githubusercontent.com/43375022/51102393-c83eb780-1804-11e9-9ad9-3dc87f46de5e.png)

and I have added the same to a dashboard along with the getSelectedMarksAsync extension from the Official page(Tutorial_4).like below.
![image](https://user-images.githubusercontent.com/43375022/51102068-6df12700-1803-11e9-9c03-a94b488fa51c.png)
I am able to capture marks when clicked on a bar chart and not a line. I want to able to listen for line too.

Note: I found that what ever we keep first in the column shelf only listens to the mark selection and not the second.
When I rearranged column shelf like below line was responding to selection not the bar.
![image](https://user-images.githubusercontent.com/43375022/51102360-a9d8bc00-1804-11e9-9c68-dc58eec81965.png)

Any Idea why this is happing?....and how to respond to all the marks.

**Comment by dsjijo** [comment]
It was a  mistake on my code.

**Comment by johnDance** [comment]
Thanks for updating the thread. Much appreciated.
