### ISSUE TITLE
Multitab dashboard throw access denied error in IE

### ISSUE THREAD

**Issue by ArunSanthosh** [tableau/extensions-api#186]
This is a duplicate of the issue reported under 
"On Tableau Server switching tabs away from one containing an extension throws continuous permission denied errors in IE11 / Edge  #182 "

However, opening as new issue since I haven't heard back on my follow up questions.

I just encountered this issue in my multi tab dashboard as well.
Works perfectly fine in firefox but gets repeated access denied in IE edge.

I see your note that this fix is available in 2019.1.
Just to be sure - you are talking of server version upgrade; not extension bundle, right?
I see server 2019.1 beta is available. Any idea on when the prod ready version will be released?
Also, Is there any workaround that can be applied to 2018.2 version ?
Please let me know. Thanks.

Regards,
Arun Santhosh

**Comment by johnDance** [comment]
Hi Arun
Sorry for the delay. We were very involved in an issue with extensions and 2019.1. 

> Just to be sure - you are talking of server version upgrade; not extension bundle, right?

Correct, the fix is internal to Tableau.

> I see server 2019.1 beta is available. Any idea on when the prod ready version will be released?

It is scheduled for releasing to operations very soon. I'm afraid I don't know how long it takes from there to the public. But it is week(s), not months.

> Also, Is there any workaround that can be applied to 2018.2 version ?

The engineer involved in the change reports that he ported the fix to both dot releases of 18.2 and 18.3. It should be available in 2018.2.5 and 2018.3.2.

Thanks again,
John

**Comment by ArunSanthosh** [comment]
John,
No issues. Thanks.Appreciate the detailed response.
This helps. We are on 2018.2.3. I will check with our admin folks on getting on to 2018.2.5.
Regards,Arun Santhosh848 218 1722

    On Thursday, January 17, 2019, 5:57:26 PM CST, John Dance <notifications@github.com> wrote:  
 
 
Hi Arun
Sorry for the delay. We were very involved in an issue with extensions and 2019.1.


Just to be sure - you are talking of server version upgrade; not extension bundle, right?


Correct, the fix is internal to Tableau.


I see server 2019.1 beta is available. Any idea on when the prod ready version will be released?


It is scheduled for releasing to operations very soon. I'm afraid I don't know how long it takes from there to the public. But it is week(s), not months.


Also, Is there any workaround that can be applied to 2018.2 version ?


The engineer involved in the change reports that he ported the fix to both dot releases of 18.2 and 18.3. It should be available in 2018.2.5 and 2018.3.2.

Thanks again,
John

**Comment by ArunSanthosh** [comment]
John,

In our last discussion, it was mentioned that the fix for this IE issue is available in 2018.2.5 and 2018.3.2
We upgraded our server environment to 2018.3.3  (I assume this should have this fix too if 2018.3.2 did)
(Tableau Server Version: 2018.3.3 (20183.19.0123.2221) 64-bit Windows) 
and continue to hit the 'Access is denied' console error along with 'An Unexpected error occurred...' dialog box. I see that the page is not becoming unresponsive now. I can continue working with the report once I close the error dialog. However, this is preventing us from rolling out the dashboard to user base since majority of end users consume via IE. Could you please check into this and let me know if any additional setting/configuration is needed at server end for the fix to be fully functional. Thanks.

Regards,
Arun Santhosh
848 218 1722
