### ISSUE TITLE
Question on Desktop extension html access mechanism

### ISSUE THREAD

**Issue by ArunSanthosh** [tableau/extensions-api#189]
Extensions team,
I have a question on the html request that is made from desktop client.
The calls made from server page has the server url passed as referrer.
Is there such a tag passed on the request made from desktop client or is it just like a direct browser call? 

(Trying to secure access to the extension url as this is company internal.
Using the domain from referrer tag lets me do this for calls from server pages.
Hence, want to know if at all similar approach can be used for desktop calls)

Regards,
Arun

**Comment by johnDance** [comment]
Hi Arun
Unfortunately, desktop does not currently provide anything for you here. However, we just created a task to add a referer header to the requests from desktop. We believe this is possible. 
Thanks for your report.
John

**Comment by ArunSanthosh** [comment]
John,
Thanks so much for the quick response and creating a task for adding referrer tag to desktop calls.
If the tag can be populated with the windows hostname + primary dns name, it will help address security setup issues similar to what I'm facing. Please pass on this suggestion to the build team.

Regards,
Arun Santhosh

**Comment by johnDance** [comment]
Hi Arun
We passed this plan past our security team, they pointed out that it provides a false sense of security. I could create something like a Postman request to your host with the referer set to the Tableau desktop string. They pointed out that the best approach is a firewall. 

As we discussed setting the referer header anyway, it was pointed out that doing so in the desktop case goes against the referer spec
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer.

If setting up a firewall is not in your plans, you could use approved IP addresses. Another idea, which can also easily be spoofed, is to use a query parameter in your URL in your manifest file. This is as insecure as the referer header, but would require an internal person sharing it externally.

Thanks,
John

**Comment by ArunSanthosh** [comment]
John,

Thanks for the detailed response.
(and sorry about the delay in getting back to you)
We will go with secured IP address ranges for tableau desktop access.
Thanks.

Regards,
Arun Santhosh

**Comment by johnDance** [comment]
Sounds good Arun.
John
