### ISSUE TITLE
Extensions don't follow system proxy settings

### ISSUE THREAD

**Issue by pavloko** [tableau/extensions-api#191]
Tableau extensions don't follow password protected proxy on Mac.

Even though Tableau application prompts for proxy username and password, the extensions fail to follow the same settings.

The extension might prompt user for username and password just like Google Chrome or Slack:
<img width="370" alt="screen shot 2019-01-30 at 8 56 41 am" src="https://user-images.githubusercontent.com/12280422/51964271-b39e2880-246e-11e9-917c-f73c9be0eec9.png">

**Comment by seanmakesgames** [comment]
Yep! We've got this one filed internally. This requires a bit of work on our end to get all sorted. I've added this github issue to the internal bug for followup. :)

**Comment by johnDance** [comment]
Sorry, we are not going to get to this anytime soon.
