### ISSUE TITLE
All values when getting data are returned as strings instead of floats, booleans, etc.

### ISSUE THREAD

**Issue by KeshiaRose** [tableau/extensions-api#192]
When returning a DataTable all the values are being returned as strings instead of their respective data types. This is not the same as [#41](https://github.com/tableau/extensions-api/issues/41) or [#121](https://github.com/tableau/extensions-api/issues/121).
![image](https://user-images.githubusercontent.com/19785852/52430865-e7ef9580-2abb-11e9-962c-1b4d6ef5be72.png)

`872428`

**Comment by LGraber** [comment]
This has been fixed in the 1.1 release of the API
