### ISSUE TITLE
dev. tools are broken in 2019.1

### ISSUE THREAD

**Issue by pavloko** [tableau/extensions-api#196]
I've updated Tableau to 2019.1 and dev. tools no longer work.
<img width="1143" alt="screen shot 2019-02-18 at 1 32 22 pm" src="https://user-images.githubusercontent.com/12280422/52948267-a98e8c00-3381-11e9-984b-5b34f6c4d696.png">

There are glitches in the extension as well. Some parts of the extension UI would become transparent or blacked out. From the image below, it seems like there is a whole in UI:)

<img width="1491" alt="screen shot 2019-02-18 at 1 36 43 pm" src="https://user-images.githubusercontent.com/12280422/52948515-43563900-3382-11e9-89a3-10ef369d39fe.png">

This is happening on Mac 10.14.3 with Chromium 47.0.2526.0. 

@seanmakesgames @KeshiaRose would appreciate your comments on this.

**Comment by seanmakesgames** [comment]
Please use latest chrome browser for debugging. 2019.1 can debug with latest version.
Try this out and let us know how it goes!

**Comment by seanmakesgames** [comment]
For the other issues, file a separate issue so we can track better! :D

**Comment by pavloko** [comment]
@seanmakesgames  Thanks for prompt reply. 

Do you mean that you've upgraded the internal browser to the latest Chrome?

**Comment by johnDance** [comment]
Not the latest, but yes, a much more recent version of chromium. Here is a snippet from the upcoming release notes:

Upgrade to the Chromium browser, which allows modern web technologies to be used with dashboard extensions (HTML 5, CSS, native ES6 support). Tableau 2019.1 now uses Qt 5.10, The Qt WebEngine is based upon Chromium 61.0.3163.99, with additional security fixes from newer versions. With this update, you no longer need to download and use a specific version of Chromium (47.0.2526.0) to debug dashboard extensions on Tableau Desktop. You can now debug extensions in Tableau Desktop using Chrome.
