### ISSUE TITLE
2019.1 content with overflow-y wouldn't display

### ISSUE THREAD

**Issue by pavloko** [tableau/extensions-api#197]
<img width="1439" alt="screen shot 2019-02-19 at 5 45 23 pm" src="https://user-images.githubusercontent.com/12280422/53027730-2ac34d00-346e-11e9-957b-1cfc969350cf.png">
<img width="1418" alt="screen shot 2019-02-19 at 5 45 29 pm" src="https://user-images.githubusercontent.com/12280422/53027734-2d25a700-346e-11e9-9760-47c57e90e92b.png">

The content with `overflow-y: scroll` masks the content that is not overflowing. 

I've also noticed that some of my layouts broke.

This happens for me on the Mac 10.14.3 and latest Tableau.

**Comment by ashwinar** [comment]
I'm not able to reproduce this issue. Could you confirm if you still see this happening on the latest Tableau Desktop ? If so, could you detail the steps you used to repro the issue?

**Comment by pavloko** [comment]
I'm not sure this is relevant anymore. If the Tableau team has upgraded the Chromium version version, then it might not be the issue anymore.
