### ISSUE TITLE
How do I open a url from Tableau Extension on Tableau Desktop?

### ISSUE THREAD

**Issue by owlstack** [tableau/extensions-api#201]
I have a web app that I've connected to a Tableau Extension and it contains a href link on the front page. 

    <div class="row">
           <a href="http://localhost:8080/download/file.pdf" target="_self">Download</a>
    </div>

The issue I'm having though is, when I click directly on the url in Tableau Desktop (after I add the Tableau Extension to Tableau Desktop), it doesn't launch a new tab or new window to open the hyperlink. Like nothing happens. 

What should I be doing to get it to launch?

**Comment by johnDance** [comment]
Hello
If I try to duplicate exactly what you have, I get the following message in my console:
Resource interpreted as Document but transferred with MIME type application/pdf

I can open it in a new window like this:
<a href="http://localhost:8080/download/file.pdf" target="_blank">Download</a>

I can open HTML in _self, but not the PDF.

If you have already tried _blank, or loading HTML, and you have your extension hosted on an https server, you will need to serve the HTML/PDF from https also.

Let me know if any of those suggestions works for you.
John

**Comment by LGraber** [comment]
Hi ... let us know if this worked for you so we can close this out or provide other pointers. Thanks

**Comment by luukvnes** [comment]
What worked for us was <target= '_blank'> instead of < target="_self"> this opes a new page in the default browser where the file is downloaded.

**Comment by romanlegeza** [comment]
It works only with Cmd+Click. Is there any way to to just a click to open a url?

**Comment by KeshiaRose** [comment]
Can you share the **exact** version of Tableau you're using and your operating system? 

One thing that I can think of that might cause this (at least from the original post) is that the file was being served on HTTP while perhaps the extension was on HTTPS. If that is the case you'll likely see an error similar to this in the [console](https://tableau.github.io/extensions-api/docs/trex_debugging.html). 
`Mixed Content: The page at 'xxxxxxxx' was loaded over HTTPS, but requested an insecure resource 'http://localhost:8080/download/file.pdf'. This request has been blocked; the content must be served over HTTPS.
`
Other than that, this should definitely work.

**Comment by romanlegeza** [comment]
@KeshiaRose we are using Tableau Server Version: 2020.3.8 (20203.21.0413.0840) 64-bit Linux and Tableau Desktop 2020.3.5 on MacOS
I implemented a simple extension with a link like
<a href="http://google.com" class="btn btn-lg" target="_blank">
And it opens a url only if I do Cmd+Click.

**Comment by KeshiaRose** [comment]
Strange, I copied your example and it worked for me both in Desktop 2020.3.5 on mac and Server 2020.3.11 on Linux. Can you try out this [sample extension](https://github.com/tableau/extensions-api/files/6919400/open_link.trex.zip) and see if any of the links open for you without cmd+click? Also, did you see any errors in the [console](https://tableau.github.io/extensions-api/docs/trex_debugging.html) when you tried to click it?

**Comment by romanlegeza** [comment]
wow, this works great! just by click

**Comment by romanlegeza** [comment]
oh I see, mine is a Sandbox extension. I just changed it to a Network one and it starts working. Is it a sandbox restriction?

**Comment by KeshiaRose** [comment]
Aha! Yes, that is a key detail! External links are not allowed in sandbox extensions. A link could include data gathered from the dashboard and therefore it opens a possibility for data exfiltration so they are explicitly not allowed. I'm actually surprised that the link works with cmd+click, @seanmakesgames is this expected behavior?

**Comment by romanlegeza** [comment]
Thanks @KeshiaRose for clarification! qq then: is there any way to replicate Navigation Buttons inside an extension? to be able to navigate inside the workbook between dashboards

**Comment by KeshiaRose** [comment]
No unfortunately not, 🙁.
