### ISSUE TITLE
Github Clone Issue

### ISSUE THREAD

**Issue by vishwasnavadak** [tableau/extensions-api#204]
git clone downloads large 300mb file that includes the tutorials folder as well which might not be necessary for everyone who is cloning it. you might want to move that to different repo.

**Comment by Kovner** [comment]
Yep this is a good idea. Thanks for pointing it out!

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
