### ISSUE TITLE
Cross tab function when exporting data

### ISSUE THREAD

**Issue by juliusvidad** [tableau/extensions-api#206]
Is there support for exporting data in a cross-tab? Like in Tableau Server?

Because I only know of getSummaryDataAsync (which is similar to choosing the Download > Data > Summary in Tableau Server)
and getUnderlyingDataAsync (which is similar to full data)

**Comment by illonage** [comment]
Hi, 

Yes, you can create an extension to export the data in a cross-tab. Craig Bloodworth created one and his code is open source -> https://github.com/TheInformationLab/Tableau-Extension-ExportData
