### ISSUE TITLE
Internationalisation of aggregations causes issues "re-hydrating" settings

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#207]
Preface: Most extensions have the need to store some setting specific to a certain column/field. In order to store which field is important we generally use [`Worksheet.getSummaryDataAsync`](https://tableau.github.io/extensions-api/docs/interfaces/worksheet.html#getsummarydataasync) in our configuration and then store the [`Column.fieldName`](https://tableau.github.io/extensions-api/docs/interfaces/column.html#fieldname) of any columns that are important to the extension. We have chosen to not use the [`Column.index`](https://tableau.github.io/extensions-api/docs/interfaces/column.html#fieldname) since it does not seem to have any guarantees of being stable (especially when a workbook is still being developed) and it is difficult to find and report errors when it changes.

We are running into an issue where users of an extension are using different locales (eg. English and French) which causes measure aggregations to be localised differently. Since the fieldName for measures includes the aggregation (eg. `SUM(Profit)`) this will also get localised (eg. `SOMME(Profit)`). We store the fieldName in settings but the localisation causes this to not match any of the fieldNames returned by `getSummaryDataAsync` when we attempt to "re-hydrate" this column.

I happen to know that the `get-summary-data` response looks something like:
```json
{
  "dataType": "int",
  "fieldName": "[federated.1dygbdp0z53tav13c6f1u1njxony].[sum:Calculation_1724597218012655617:qk]",
  "fieldCaption": "SUM(Days to Ship (Actual))",
  "isReferenced": true,
  "index": 15
}
```
What we are getting from `Column.fieldName` seems to be the internal `fieldCaption`, the actual internal fieldName seems to be a unique field identifier in a workbook. Maybe this can be exposed as an extra `id` field on `Column`? It is also important that this works retroactively as we wouldn't want newly developed extensions to not function on previous versions of Tableau but i'm not sure what the impact of this change would be in that regard.

**Comment by johnDance** [comment]
Thank you for your report and the investigation that you made. We have run into several issues with our current use of fieldName. For example, another issue is setting a filter on a field in a secondary data source. We will be investigating how to resolve the issues. As you suggest, a fieldId is probably needed.

Thanks,
John

**Comment by rplp** [comment]
We also need this feature to solve internationalization issues. I believe the best approach would be besides having the fieldId being able to then match it with the full field metadata.

**Comment by johnDance** [comment]
Thanks for the link. I'll link up this issue with our internal issue tracking field id needs.
