### ISSUE TITLE
A few issues with resizing the extension

### ISSUE THREAD

**Issue by sravikiran** [tableau/extensions-api#208]
Hi,

We are building a tableau extension that has to respond when a user resizes it. It renders content on the extension based on the available width. We are currently facing the following two problems because of this:

 - The extension page reloads whenever the extension is resized in the Tableau workbook online view using any browser like Chrome or Firefox
 - We need a way to resize the extension dynamically to a size when the user clicks on a button. I tried the ways in which a browser window can be resized using `window.resizeBy` or `window.resizeTo`, but they didn't work

Please let me know if there are ways to solve these using the Tableau extensions API or if there is any plan to include these features in the future?

**Comment by Kovner** [comment]
You're asking for a way to resize the Extension zone in the dashboard via the Extensions API? If so, we don't have that in the API but we will likely build a way to resize dashboard zones via the API at some point in the future.

**Comment by sravikiran** [comment]
@Kovner Thanks for your reply here and on the forums.
1. Yes, the extension is reloading whenever we resize it on the web. We will keep checking your release notes for the fixes and let us know if you create an issue here for the bug.
2. It would be handy to have the API to resize the extension dynamically. Thanks for considering this.

**Comment by johnDance** [comment]
We now have the ability to move & size dashboard zones.
