### ISSUE TITLE
https connection not working in tableau desktop

### ISSUE THREAD

**Issue by gmYusuf** [tableau/extensions-api#209]
I create a extension its working on localhost,this extension working well with http connection but when I open with https (node node_modules/http-server-ssl/bin/http-server-ssl -S 8765). Tableau desktop dont show this extension. It just show white frame

**Comment by johnDance** [comment]
Hello
Follow the steps here: https://tableau.github.io/extensions-api/docs/trex_debugging.html to attach a debugger. The console should give some information about not loading.
John

**Comment by LGraber** [comment]
besides localhost, we only support loading an extension whose url starts with https. Please let us know if you were able to figure out what is happening by debugging the console. You could also use Fiddler (if you are running on windows) to see some of the wire traffic and see if there are any failures there.

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
