### ISSUE TITLE
GET /favicon.ico gets a 404

### ISSUE THREAD

**Issue by JeffStrauss18** [tableau/extensions-api#211]
I have an extension published to our internal github bitbucket repository and am using the pages feature to serve up the html / js files.  It can't find the favicon.ico because the GET is looking for it at root of github instead of in my app sub-directory (https://git.cnvrmedia.net/pages/BI/tableau-extensions).  Can you offer any advice?

**Comment by geordielad** [comment]
Add a LINK element to your extention's html page(s): https://en.wikipedia.org/wiki/Favicon

**Comment by JeffStrauss18** [comment]
thank you!!!!  This did the trick, interestingly enough I had to modify the path dependent on whether it was the main page or config page.

Main page: <link rel="icon" href="../favicon.ico">
Config page: <link rel="icon" href="../../favicon.ico">
