### ISSUE TITLE
Run Extensions API, even when the dashboard is not visible

### ISSUE THREAD

**Issue by forainychen** [tableau/extensions-api#225]
Is there a way to force extension to run even the dashboard is not visible?

In Tableau Server or Tableau Online version 2018.3 and later, when the browser window is not visible (that is, when the browser window Tableau is running in is minimized or in the background), the Extensions API method calls are blocked and an error object is returned.
https://github.com/tableau/extensions-api/blob/01a69b13233b3b6ccdbdc8c32391bdcb0103279c/docs/trex_error_handling.md

However, for example, for the below extension, which is used to update the data, then update the view subsequently, 
https://github.com/tableau/extension-data-driven-parameters

I would like to let the extension to update the data, when the dashboard is not visible, and when I switch back to the dashboard, all data and view has been done on update.

**Comment by Kovner** [comment]
Hi,
The blocking of Extensions on dashboards that were not visible was causing more troubles than it was solving and so we turned that functionality off in 2019.1. Extensions that are not visible will execute.
