### ISSUE TITLE
Provide es6 module compatibility.

### ISSUE THREAD

**Issue by rcollette** [tableau/extensions-api#228]
You are already using webpack so it should be quite easy to build this library so that it can be an importable module.

Right now, I get no IDE (WebStorm) coding assistance because `tableau` is referenced as a global variable from my extension code.

**Comment by demartsc** [comment]
We should definitely be able to install this as an npm module. +1 to this ask please!!

**Comment by Kovner** [comment]
You can do this with the TypeScript module: https://tableau.github.io/extensions-api/docs/trex_typescript.html
We were debating internally whether that solves the request or not, but then I thought it best to just ask. Does using the TS module help?

**Comment by ashwinar** [comment]
We currently have published the type declaration files to npm at @tableau/extensions-api-types. That should help with IDE coding assistance. So, just to understand, would that help in your use-case with WebStorm IDE?

**Comment by rcollette** [comment]
That should help, although the trend is to simply package them with the library itself.   
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I have moved on to another project at this point and my license re-allocated to another person so I won't be able to get in there and verify anything.

**Comment by rcollette** [comment]
Ah wait, I have to switch gears in my head here for a second, coming off of standard browser coding.

The types are for a global JS bridge.  There isn't really SDK *code* per-se (i.e. I don't need to do tree shaking and such).   Therefore the type module should be sufficient if I'm getting this straight.

**Comment by ashwinar** [comment]
Yupp, that's correct. Also, yes we do agree packaging with the extensions-api and publishing it to npm is the trend, but that requires a little more effort from our side. We already have an item in our backlog to tackle this.

If this helps in your use-case, feel free to close the issue.
