### ISSUE TITLE
Feature: Opt out of forced HTTPS via a server setting

### ISSUE THREAD

**Issue by kostenickj** [tableau/extensions-api#230]
I would really like a way to "opt out" of HTTPS only extensions traffic. It Really causes a nuisance when deploying to on-prem infrastructure. Many of our clients are just using IP addresses to access their internal tools and don't know how (or want to know how) to get proper HTTPS working without significant help from us. A server setting allowing non HTTPS traffic for extensions would be handy.

**Comment by johnDance** [comment]
Sorry, we are not going to get to this in any near timeframe.
