### ISSUE TITLE
Copy and paste dashboards with extension results in an error

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#236]
Hello,

When I copy a dashboard with extension and paste it in a new workbook I get an error:
![image](https://user-images.githubusercontent.com/16118919/58859827-07ce4900-86ab-11e9-917f-f499b07ef813.png)

Tested with Tableau 2019.2.0

**Comment by johnDance** [comment]
I have duplicated this internally. We will get it fixed. Thanks for bringing it to our attention.

**Comment by bcantoni** [comment]
Closing as fixed.
