### ISSUE TITLE
Set range for parameter in extension

### ISSUE THREAD

**Issue by mma-xyt** [tableau/extensions-api#242]
Hello.
I need to initialize parameters based on given data. I've been playing around with Data-Driven Parameters extension and couple others. However, I haven't seen a possibility to set min or max value of a parameter of type range. I guess API doesn't allow it. 
Have anyone managed to set a range of values from API or maybe is it possible to add such functionality?

**Comment by Kovner** [comment]
The general philosophy of the Extensions API functionality is that it can do what the dashboard consumer could do manually. A dashboard consumer can change the value of a parameter but not its min-max and so thats why the API cannot do that either.

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
