### ISSUE TITLE
FR: getUnderlyingDataAsync add pagination support

### ISSUE THREAD

**Issue by BobSenturus** [tableau/extensions-api#245]
We have a use case with many (hundreds of thousands of rows of data) underlying the charts we're working with.

It would be ideal to be able to pass in 2 new GetUnderlyingDataOptions to getUnderlyingDataAsync that specify "offset" and "rowcount".  That would allow for larger underlying datasets to be paged through and processed by the extension.  The sort order of the underlying data set would need to be static in order for that paging to work.

Or is there another approach for working with large data sets and extensions?

**Comment by Kovner** [comment]
Yes we really really want a paging system for querying data in the api, but unfortunately that's not something the internal query engine of Tableau currently supports so it would be a pretty big project. I think we'll have it some day, but I can't tell you when. Sorry!

**Comment by BobSenturus** [comment]
Glad to hear it is known.  It get my vote as top missing feature for the extension API!

**Comment by merlijnbuit** [comment]
Any updates on this issue? We are facing the same challenge where customers want millions of rows in SuperTables. Pagination would be super helpful to speed up the 'getting data' part.

**Comment by Kovner** [comment]
Nope same story: It's a big architecture-level change that another team would handle and it is not scheduled. We continue to do our best to get it on the roadmap for the future.
