### ISSUE TITLE
How to catch page changed event?

### ISSUE THREAD

**Issue by uraxurax** [tableau/extensions-api#265]
I'm using pages shelf in my worksheet.
https://help.tableau.com/current/pro/desktop/en-us/buildmanual_shelves.htm#pages-shelf

So I call addEventListener() because I want to detect the page changed event.
https://tableau.github.io/extensions-api/docs/trex_events.html

However, I cannot detect it even if I use all event types.
I used following code to check the detection.
- Samples/Filtering : FilterChanged
- Samples/Parameters : ParameterChanged
- Samples/UINamespace-sandboxed : SettingsChanged
- Tutorial\Part_6 : MarkSelectionChanged

So I want to confirm whether current extension API support page changed event.

**Comment by johnDance** [comment]
Unfortunately, the API doesn't yet support page changed events. It is definitely on my wish list.
John

**Comment by uraxurax** [comment]
Dear John Dance,

Thank you for your comment.
I understand the current status.

Regards,
Hiro

**Comment by johnDance** [comment]
We now support dashboard layout changed events.
