### ISSUE TITLE
https://github.com/tableau/extensions-api/tree/master/Tutorial/ReactVersion/ReadMe update ?

### ISSUE THREAD

**Issue by Bricebr** [tableau/extensions-api#274]
should we care about the "npm install" return:
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated isparta-instrumenter-loader@1.0.1: isparta-instrumenter-loader is deprecated. Please use isparta-loader instead
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

> phantomjs-prebuilt@2.1.16 install C:...\extensions-api\Tutorial\ReactVersion - sandboxed\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:...AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Using proxy ...
Receiving...

Received 17767K total.
Extracting zip contents
Removing C:...\extensions-api\Tutorial\ReactVersion - sandboxed\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C...AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1570173452663\phantomjs-2.1.1-windows -> C:\...\extensions-api\Tutorial\ReactVersion - sandboxed\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\...\extensions-api\Tutorial\ReactVersion - sandboxed\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> core-js@2.6.9 postinstall C:\...\extensions-api\Tutorial\ReactVersion - sandboxed\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**added 1049 packages from 1468 contributors and audited 7517 packages in 241.455s
found 38 vulnerabilities (16 low, 5 moderate, 14 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details**
**BAD IDEA**
**IF you force the fix to update/upgrade modules, it leads to break as**
$ npm start

> @0.0.1 start C:...\extensions-api\Tutorial\ReactVersion - sandboxed
> npm run lib & node server.js --env=dev

> @0.0.1 lib C:\..\extensions-api\Tutorial\ReactVersion - sandboxed
> copyfiles -f ../../lib/tableau.extensions.1.latest.js src

C:\...\extensions-api\Tutorial\ReactVersion - sandboxed\cfg\dev.js:21
    new webpack.NoErrorsPlugin(),
    ^

TypeError: webpack.NoErrorsPlugin is not a constructor
    at Object.<anonymous> (C:\...\extensions-api\Tutorial\ReactVersion - sandboxed\cfg\dev.js:21:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at buildConfig (C:...\extensions-api\Tutorial\ReactVersion - sandboxed\webpack.config.js:28:16)
    at Object.<anonymous> (C:...\extensions-api\Tutorial\ReactVersion - sandboxed\webpack.config.js:32:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 start: `npm run lib & node server.js --env=dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bcantoni** [comment]
I believe we can consider this fixed with all the updates that have occurred since.
