### ISSUE TITLE
how to add modules properly to the npm ?

### ISSUE THREAD

**Issue by Bricebr** [tableau/extensions-api#279]
from a package.json of an extension, there is a list of modules not present in the default sandbox env.
I tried npm install
 @material-ui/core@^4.0.0-rc.0
 @material-ui/icons@^4.2.0, 
 file-saver@^2.0.2, 
 react-router-dom@^5.0.1,
 react-scripts@^3.0.1, 
 xlsx@^0.14.3, 
but still unable to load an index.js with this syntax:
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import Main from './containers/Main';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<Main />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

localhost:8696 says: 
Desktop bootstrapping succeeded!
index.html:33 Extension sandbox script loading...
index.html:157 Extension sandbox window.load done.
Uncaught SyntaxError: Unexpected token import

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
