### ISSUE TITLE
Select options get "hung" when moving a dialog without choosing an option.

### ISSUE THREAD

**Issue by lcsixp** [tableau/extensions-api#285]
Hey there,

We have observed an unusual behavior between the select options and a dialog window opened using the extension javascript API (tableau.extensions.ui.displayDialogAsync).

When we click the dropdown and expose the options, if we do not choose any option and move the dialog around we noticed that the options get hung in the place where they first showed (See picture below).

![image](https://user-images.githubusercontent.com/57663873/68663380-70f99880-0536-11ea-8a77-285f3554529f.png)

To simulate the behavior we found in our extension, we've slightly modified the Filtering extension sample from this repository, adding a button that would open a dialog with an HTML page that contained a div and a select tag. We have attached the sample.

Have you experienced this kind of behavior?

Best regards,
Luciano

[extensionSample.zip](https://github.com/tableau/extensions-api/files/3835848/extensionSample.zip)

**Comment by Kovner** [comment]
Hi @lcsixp, I don't think we've seen this before, but I just used your sample to reproduce this issue. I will log it internally.

**Comment by Kovner** [comment]
This has been fixed. The fix will be released with Tableau 21.2
