### ISSUE TITLE
Tableau on windows with Chrome 80 - opening in debug mode causes an error

### ISSUE THREAD

**Issue by jstrauss18** [tableau/extensions-api#291]
It works with Chrome 79.
--------------------------------------------------------------
Running Tableau 2019.4.3

C:\Program Files\Tableau\Tableau 2019.4\bin>tableau --remote-debugging-port=8696

Wait for desktop to open.  Then permit extension to run.  I believe this happens with both running from a remote web server and with using localhost:8765

Go to http://localhost:8696 and then click on inspectable page.  It shows blank, and upon looking at the console, it shows:

inspector.js:2964 Uncaught TypeError: document.registerElement is not a function
    at Object.UI.registerCustomElement (inspector.js:2964)
    at inspector.js:2976
    at inspector.js:2978

**Comment by johnDance** [comment]
Jeff
We just discovered this ourselves yesterday. It appears that a deprecated function has been removed in Chrome version 80, but it is still in use in the Qt/Chromium we are using for desktop.

We are changing our documentation. Unfortunately you will need to use a version 79 of Chromium to debug extensions in desktop.

It can be a little confusing trying to find a previous build of Chromium. Here is version 79: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/706915/

We are sorry for the inconvenience.
John

**Comment by JeffStrauss18** [comment]
thx for the quick response!  For now, we have an isolated version of Chrome 79 and hopefully it won't automatically update...Otherwise we'll have to revert to using Chromium.

Will Chrome ever work again?

**Comment by johnDance** [comment]
Yes. We need to update our internal version of Qt/Chromium. We are reaching out to the team in charge of that work to alert them of this new issue, and check on timelines. Unfortunately, even in the best case, it will be months, not weeks. 

John

**Comment by johnDance** [comment]
By the way... do not check your version in Chrome. That will kick off auto-update. There are some web pages that describe how to turn off auto-update. But remember that auto-update is your friend in normal web browsing.  I just added a taskbar shortcut to Chromium 79. I open that when I want to debug.
John

**Comment by TomNes94** [comment]
I get the same error in Firefox (73.0 64-bit). Likewise for Microsoft Edge 42.17134.1098.0. 
Tableau version is 2019.4.3.

**Comment by ArulkumarSambasivam** [comment]
We can solve through following steps
Step 1: Got to chrome 
Step 2: Enter `chrome://inspect/#devices`
Step 3: Enable 'Discover network targets' 
Step 4: Click 'Configure' button
Step 5:  Add  'localhost:Tabluea Port'
Step 6: Click 'Done'
Now you can see the debug option 
![image](https://user-images.githubusercontent.com/19467115/75140405-d99b0880-5714-11ea-92e5-f927cad0be79.png)

**Comment by chavikau** [comment]
Hi,
tried install chromium version 79 with this link:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/706915/
and got an error:Aw, Snap, something went wrong while displaying this webpage

thanks

**Comment by johnDance** [comment]
Hmmm... That is the correct location. Verify that you downloaded chrome-win.zip. It should give you a file Win_x64_706915_chrome-win.zip. After unzipping, chrome.exe should be in the chrome-win folder. Choosing "About Chromium" should give you Chromium: Version 79.0.3945.0 (Developer Build) (64-bit)

**Comment by jdavidbakr** [comment]
Curious if this has been fixed in the last year?  I just started trying to build extensions and am getting the error described.  Chrome version Version 88.0.4324.192.

**Comment by johnDance** [comment]
Hi @jdavidbakr 
You might be running into issues with versioning in the debugging protocol. See this part of our extension API documentation for help on which version of Chrome/Chromium to use:
https://tableau.github.io/extensions-api/docs/trex_debugging.html

Let me know if I misunderstood your question. 
John

**Comment by jdavidbakr** [comment]
Yes @johnDance, above you mentioned that the fix would be coming so I was wondering how close it is so we can use the current version of Chrome instead of using an older Chromium.

**Comment by johnDance** [comment]
Any of the February maintenance releases of 2020.2+ will be able to use Chrome.
2020.2.11, 2020.3.6, 2020.4.2, and the upcoming 2021.1
Thanks!
John

**Comment by bcantoni** [comment]
Closing as fixed.
