### ISSUE TITLE
[SUGGESTION] - Dashboard refresh

### ISSUE THREAD

**Issue by lcsixp** [tableau/extensions-api#294]
Is there a way to add an API call that refreshes the dashboard or a certain worksheet after some event happens on the extension?

We are working on an extension that [writes-back](https://extensiongallery.tableau.com/products/114) data and we wanted to see changes occur in real-time after insertion.

Thanks!
Luciano

**Comment by johnDance** [comment]
Does DataSource.refreshAsync meet your needs? I've copied the documentation here so you can easily check:

This call has the same functionality as clicking the Refresh option on a data source in Tableau. This does not refresh an extract.

Note: The refreshAsync() method is intended to be used in scenarios where manual interaction causes a need to refresh the data in the Tableau visualization. The method is not, as currently designed, meant to support or emulate streaming or live visualizations. Extensions that use the method to refresh aggressively or automatically can cause issues on Tableau Server and Tableau Online and are subject to being blocked by the Tableau Online administrator.

This call does not currently support refreshing live Google Sheet data sources.

Returns Promise<void>
Promise that resolves when the data source has finished refreshing.

**Comment by Kovner** [comment]
@gauravvats1123 Sorry no there's no way to refresh the extract and thats intentional: End-users can't choose to refresh a datasource extract: only dashboard authors can.
