### ISSUE TITLE
Dashboard loading with no data

### ISSUE THREAD

**Issue by aksharj** [tableau/extensions-api#295]
Hi,

Is there a way i can use the extensions api to notify when a dashboard loads with blank data. We see that sometimes under heavy load the when the dashboard is accessed, it loads but no data is shown.

**Comment by Kovner** [comment]
You could use 'getSummaryData' to see if the returned table is empty. Does that fit the use case?

**Comment by aksharj** [comment]
thanks @Kovner, thats works. would be great to have a property thought that indicates if there were no results.

**Comment by aksharj** [comment]
Hi @Kovner, I have been able to use the `getSummaryDataAsync` method to see if dashboards loads with blank data. However, when i use it I see the tableau spinner again. This means the user sees the tableau spinner twice which is a bit confusing. Do you know if there is a way to execute this without spinner being loaded again?

Thanks.
