### ISSUE TITLE
Extension API error is making the extension reload the whole page preventing the usage, since 2019.4.

### ISSUE THREAD

**Issue by lcsixp** [tableau/extensions-api#298]
Hey there,

Since the new release of 2019.4 we have identified a scenario where when we attempt to use an extension with a user that has not Administrator Role and deploying the extension in the dashboard causes the whole dashboard to get stuck in a reloading cycle.

After some investigation, we notice this happens when the extension attempts to perform a saveAsync() of the settings. We used the Write-back extension both the paid and the free version and the issue seems to happen for both when a saveAsync() of the settings is requested from the API.

We are reaching out since it also throws the InternalError code from the API. Find attached a print screen of the error the console prompts and a gif of the dashboard reloading. In the console, there are some logs and its at the moment where we call saveAsync() that the dashboard reloads. Again, this scenario does not happen if it is an Administrator using the extension.

Does this happen to anyone else?

Luciano,
Write-back Team
![errorTableauAPi](https://user-images.githubusercontent.com/57663873/76524910-c9985e00-6462-11ea-9df1-e8fc7146af3e.png)

![apibug](https://user-images.githubusercontent.com/57663873/76528630-0cf5cb00-6469-11ea-85c2-3a07a12f6129.gif)

**Comment by Kovner** [comment]
Our error handling should be better, but that error is intended: You are not allowed to use saveAsync during 'view' mode. Only during 'authoring' mode.
