### ISSUE TITLE
Data driven alerts - API?

### ISSUE THREAD

**Issue by aksharj** [tableau/extensions-api#300]
Hi,

Sorry, I am not sure if this is the correct place to ask this question as its not a issue. But i am unable to find any relevant information.

Is there a way using the API I can create data driven alerts? For example, i apply certain filters and save it as a view. Can i get notified when new data is added for that filter combination?

Any help in this would be really great!

Thanks.

**Comment by Kovner** [comment]
Not really...
Using the Extensions API, you could query the data in the dashboard and send some kind of alert, but an Extension only 'lives' while a user is interacting with the dashboard, so it won't be able to query the data while a user is not interacting.
There really aren't any APIs around data driven alerts, but there is a non-API feature for data driven alerts.

**Comment by aksharj** [comment]
Thanks @Kovner for your reply. Do you know if there are any plans to create a API for data driver alerts?

**Comment by Kovner** [comment]
It has been discussed, but there are no formal plans.
