### ISSUE TITLE
Uncaught (in promise) This extension is not running inside an iframe, desktop, or popup window. Initialization failed.

### ISSUE THREAD

**Issue by chavikau** [tableau/extensions-api#301]
I have installed tableau desktop (2019.4), tried to add extension and I  have a problem 
so i tried to debug, i ran the following command:
"C:\Program Files\Tableau\Tableau 2019.4\bin\tableau.exe" --remote-debugging-port=3000
tried to open this in chromium and got ab error:
(index):1 Uncaught (in promise) This extension is not running inside an iframe, desktop, or popup window. Initialization failed.

Can you help me??

Thank you

**Comment by Kovner** [comment]
Yes, it seems like you might be opening the Extension in the Chromium browser? Instead you should add the Extension to the dashboard and then go to localhost:3000 in Chromium to debug.

**Comment by chavikau** [comment]
Thanks for the response,

I tried now again
first 1 ran the command,
Then I opened the extension and after this open chromium - and got the error - and didnt get the option to debug

Is there anything didn't do right

Thanks

**Comment by johnDance** [comment]
Hi, 
Just to be clear...
1. "C:\Program Files\Tableau\Tableau 2019.4\bin\tableau.exe" --remote-debugging-port=3000
2. Load your workbook, and go to the dashboard that has your extension
3. Click Okay  in the "Allow Extension" dialog.
4. Open chromium on localhost:3000, select your extension from the list (that might be one item long)
You should then be able to debug.
Note that after step 4, do not press F5. That reloads your extension, but it loads it directly in the browser so that you get the initialization failed error.

Hopefully that helps.
John

**Comment by chavikau** [comment]
Hi John,

Thanks for the response...

I did all the steps you said - my problem is when I open the chromium I don't have options to choose anything

what's my wrong?

thank you so much!!

**Comment by johnDance** [comment]
Hmmm... could you share a screen shot? I'd love to see the terminal where you launch tableau with --remote-debugging-port=3000, also Tableau with the extension running, and finally Chromium after loading localhost:3000. 

Perhaps together we can spot something that is going wrong. Thanks!
John

**Comment by utkarssh01** [comment]
Hi John,

I'm facing an issue while downloading a file from Dockerized application to my local system.

Its an extension on Tableau, and I'm expecting while downloading a report from that Tableau extension it should download.

But its giving an error in Console when download for report method initiates:
Uncaught (in promise) This extension is not running inside an iframe, desktop, or popup window. Initialization failed.

It would be great if you could please help me out with that... if you need more details I'll be providing it to you.


Thanks
Utkarsh Sharma

**Comment by johnDance** [comment]
Hi Utkarsh
It sounds like the extension is running outside of Tableau. Did you install the extension by dragging it from the objects panel into your dashboard? Could you share the workbook with us? If your workbook has confidential information, perhaps a test workbook that also duplicates the issue.

Could you also explain your Tableau and docker set up? Are you using Tableau server, or Tableau desktop?

Thanks,
John

**Comment by utkarssh01** [comment]
Hi John,

Thanks for replying back!

Yes, I installed extension by dragging it from the objects panel into dashboard. 

Workbook is in Test environment I'm working on, its owned by our client so not sure if it will be correct to share it on public platform.

We are using Tableau server owned by our client, docker setup is done to fulfil a use case of our client that the users can run the application (which is a Tableau extension) on dockerized platform.

We have created dockerized images of the code and running the code in container, all other things remains the same.

Steps:
Initially will go to Tableau server website and login , select Site, then go to dashboard.
1. I drag and drop the extension from object panel to Tableau dashboard.
2. Then, .trex file is selected from my extensions
3. Configure the extension
4. It will launch the client application in a separate pop up window
5. There I downloads a report and it redirects me to the parent window
6. There a new tab opens where I believe that report(pdf) should be opened, but it opens front page of the application and in devtools window on console tab it gives that error "Uncaught (in promise) This extension is not running inside an iframe, desktop, or popup window. Initialization failed."

We are not facing that issue where we are running the application using springboot in Eclipse, there also reports open from local file system, but may be not sure some issues with docker local setup.

Please let me know if you could help any further.

Thanks 
Utkarsh Sharma

**Comment by bcantoni** [comment]
I'm going to close out this older issue because there were two different reports mingled together here.

@utkarssh01 and @chavikau, if you are still facing this problem would you please open new issues with current status of what you've tried?
