### ISSUE TITLE
Extension - transparency

### ISSUE THREAD

**Issue by jstrauss18** [tableau/extensions-api#302]
Hi there.  Transparency is available within desktop for worksheets and filters, but not extension objects.  Please make this available as extensions have transparency within server, and it needs to be consistent on desktop.  I am referring to the community based react annotation extension.  Thank you!

**Comment by johnDance** [comment]
Hi
This is a high priority, but we just need to get it scheduled. The react annotation extension is awesome, and we would love to see it working on both desktop and server.
John

**Comment by bcantoni** [comment]
Transparency should now be supported with [Extensions API Release 1.7](https://tableau.github.io/extensions-api/docs/trex_release-notes.html#tableau-dashboard-extensions-api-version-17).

**Comment by jstrauss18** [comment]
how to enable transparency for network extension?  How does sandbox extension do it?

**Comment by bcantoni** [comment]
@jstrauss18 transparency is only supported for sandbox extensions. I believe it's not possible to do that in the network extension because of the security concerns around click jacking.

**Comment by jstrauss18** [comment]
thx.  Is sandbox extension code available somewhere so that I can deploy internally?
