### ISSUE TITLE
Reverse order on data from getSummaryDataAsync 

### ISSUE THREAD

**Issue by rplp** [tableau/extensions-api#305]
We are using getSummaryDataAsync  to capture the data from a Tableau sheet and then display on the extension. For dimensions such as dates, keeping the original order is very important. However we have noticed that data most of the times is being obtained in reverse order. This behavior is similar to what is obtained on View Data. The image below shows the reverse order on sub-categories. 

Is there any way to control this and make the order to be always non-reversed?

![image](https://user-images.githubusercontent.com/1006570/78161343-32a93b00-743d-11ea-9c91-7b092c6abf05.png)

**Comment by johnDance** [comment]
Hi
I'm afraid our implementation shares the same backend work as View Data in the UI. There currently isn't any option to control the order. Notice that this order would change based on many user interactions with the worksheet, such as a simple sort. This position information is not part of the  summary data information at all.

We would like to implement MarkInfo, which is currently not implemented. Perhaps the position information could be part of MarkInfo. We don't have a timeline for implementing MarkInfo.  

Sorry for the bad news.
John

**Comment by rplp** [comment]
Hi John, 

Thanks for providing feedback, lets see if we can mitigate the bad news.  

We want exactly to take advantage of the user interactions so that they can easily configure the viz to be used together with Write-Back. So what I meant by controlling is to ensure that we would always get the data in the same order established by the user. What we noticed is that there is a clear correlation between how the user sorts and how it is shown for instance on View Data, so even if the actual information is not part of summary, the elements position and sorts is driving it. I am assuming since this is shared it won't be something easy to change, so is there any chance you could share how the data set is built so we could reverse it on our code? This has some risk but with a combination of best practices on the Tableau viz and our code we could get a deterministic result. 

Markinfo corresponds to getting additional metadata about the Mark? That would be great :)

Best regards, 
Ricardo Pires

**Comment by johnDance** [comment]
Ricardo:
I am asking an engineer who creates the layout of the data for the visualization. I'll get back with you.

Stay healthy,
John

**Comment by johnDance** [comment]
Ricardo:
Normally the order will be reversed, but this is really an implementation detail. We cannot promise that in some cases, or in the future, the order will change. I think your best route is to do something temporary now, but hold out for MarkInfo. 
Sorry again,
John

**Comment by rplp** [comment]
John, 

Thanks for checking this out. We will create the temporary implementation. 

Best regards, 
Ricardo Pires

**Comment by bcantoni** [comment]
Closing as won't fix based on the discussion above.
