### ISSUE TITLE
using HTML5 Drag n Drop API doesn't work

### ISSUE THREAD

**Issue by sgratzl** [tableau/extensions-api#310]
I'm trying to implement an extension which uses the HTML5 Drag n Drop API (https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API). While the `dragstart` and co events work, it immediately shown an not allowed cursor and no `dragEnter` or `dragOver` events are fired. It seems like that the window itself (in this case a configure popup) is prohibiting the drop operation.

Any idea what I can do to make it work?

**Comment by merlijnbuit** [comment]
Hi Sgratzl,

We have the same challenge.
you can use alternative packages to get this to work like https://github.com/atlassian/react-beautiful-dnd

Merlijn

**Comment by sgratzl** [comment]
thx, in the meanwhile I also implemented a custom solution without the native api

**Comment by merlijnbuit** [comment]
Great! would you mind sharing the package or a snippet here? So other developers can learn from it?

**Comment by sgratzl** [comment]
in the end I used something similar to this: https://codepen.io/sgratzl/pen/MWaoOXz There is for sure a library which would do a similar thing.
