### ISSUE TITLE
Communicate between same extensions instances in the same dashboard

### ISSUE THREAD

**Issue by mmoraisluis** [tableau/extensions-api#311]
Hello,
We came across a use case in which we wanted several instances of the same extension in the same dashboard to be able to communicate between them. One of the ideas would be to have a kind of settings shared by the various instances. The use case more specifically is if we have to log in to our extension this would facilitate the process because after logging in the first instance we could pass the login token to other existing instances on the same dashboard, instead of having 3 login screens.
Have you considered allowing any type of communication between extensions on the same dashboard?

Marcos

**Comment by merlijnbuit** [comment]
You could communicate between extensions by hijacking a parameter in the dashboard to sync settings between extensions. It will not be the fastest way but it kinda works.

**Comment by johnDance** [comment]
@mmoraisluis, @merlijnbuit - I'm happy to announce that when 2020.4 is released, localstorage or cookies can be used, and shared (between extensions in the same domain) on both desktop and server.
John

**Comment by bcantoni** [comment]
Closing as fixed.
