### ISSUE TITLE
Extensions not working on iPhone Tableau Mobile app

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#312]
Hi,

I am testing extensions for a customer of us on the Mobile app.
I am using a iPhone XS with IOS 13.3.1.

Chrome for IOS: Working
Safari for IOS: Not working by default
Tableau Mobile App: Not working 

I changed some of my settings of Safari under the 'private and security' tab. I have disabled 'Do not Track' and 'block all cookies' and extensions are working on Safari for IOS now.

However I was assuming these same settings would apply to the Tableau Mobile app with the built in browser. But this is not the case. No extensions are working on the mobile app. 

This has a very big impact for this large Tableau user. 

Do you have any tips on getting extensions to work on Mobile?
Does this require a change in the Mobile App?

**Comment by johnDance** [comment]
Merlijn:
Are these sandboxed extensions you are testing, or just any extension?
Thanks,
John

**Comment by merlijnbuit** [comment]
To be specific: Any extension developed by AppsforTableau.

Sandboxed aren't working because the customer want on-premise extensions only.

**Comment by johnDance** [comment]
Okay, thanks. We will investigate.

**Comment by johnDance** [comment]
Hi Merlijn: 
It appears that the AppsforTableau web server doesn't play well with the latest versions of Safari. 

Safari 13.1 on MacOS Catalina cannot run your extensions. I see the following errors both on Catalina, and on iOS 13.3.1:
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (bootstrap.min.css, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (commons.js, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (index.js, line 0)

Meanwhile, socket.io.js loads fine.

If I load your html directly, everything loads. I'm wondering if there is something in the request header when it comes from an iframe that your server doesn't like.

Let us know what you find.
Thanks,
John

**Comment by merlijnbuit** [comment]
Hi John,

Thank you for investigating!
Are you debugging mobile or are you trying to load the extension in your browser directly? 
We are doing checks on our machine on the location of the request.

In your experience, should all extensions work on mobile?

**Comment by johnDance** [comment]
I was running directly in the browser on both an iPad, and iOS Simulator. I then ran on Safari on MacOS, and found the same behavior there.

I also tried (but did not debug) in Tableau Mobile. I have another extension that I tried in all three places.

We have some minor reported bugs on Tableau Mobile, but in general, yes, extensions should work on mobile.

**Comment by merlijnbuit** [comment]
I have fixed it, thank you for your investigation :)

**Comment by johnDance** [comment]
Great news. Thanks for the update.
