### ISSUE TITLE
Feature Request:  More support for Sets

### ISSUE THREAD

**Issue by myfriendedward** [tableau/extensions-api#329]
It would be great to have the ability to add/remove set members via the API.

Example use case:  My dashboard is using sets in a filter-like fashion (with sets being used instead of filters for specific detailed reasons not important here).  User interaction with my extension needs to add/remove set members (very similar to how extensions sometimes need to adjust filters).

**Comment by bcantoni** [comment]
We don't have any plans to expose sets through the API, so I'll close this one out.
