### ISSUE TITLE
Followed your steps to install tableau extensions...

### ISSUE THREAD

**Issue by radhakrishna10281** [tableau/extensions-api#33]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose stack Error: Cannot find module 'github-url-from-git'
4 verbose stack     at Function.Module._resolveFilename (module.js:469:15)
4 verbose stack     at Function.Module._load (module.js:417:25)
4 verbose stack     at Module.require (module.js:497:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:2:22)
4 verbose stack     at Module._compile (module.js:570:32)
4 verbose stack     at Object.Module._extensions..js (module.js:579:10)
4 verbose stack     at Module.load (module.js:487:32)
4 verbose stack     at tryModuleLoad (module.js:446:12)
4 verbose stack     at Function.Module._load (module.js:438:3)
5 verbose cwd C:\Users\09137812\Documents\My Tableau Repository (Beta)\Extensions
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
8 error node v6.11.4
9 error npm  v3.10.10
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'github-url-from-git'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by d45** [comment]
I am sorry to hear that it didn't work for you. I'm not sure exactly what happened from the log. Did you download or clone the GitHub repository? 
Try running **npm install** from the `extensions-api folder` where you either cloned or downloaded and extracted the zip file.   This folder will have the `package.json` file. 
After you run the install script, run **npm start**.

**Comment by geordielad** [comment]
See this issue. It might be a windows installer bug if you updated from 4 to 6 using an msi: https://github.com/npm/npm/issues/11383

**Comment by lbrendanl** [comment]
@radhakrishna10281 did @geordielad suggestion help resolve the issue?  Will close this if it's been resolved.

**Comment by datocrats-org** [comment]
I followed the instructions, and just see the Learn more link under extensions.  

The npm server is runing because when I navigate to http://127.0.0.1:8765/ I see the index.html file content.

Do you need to copy anything other than the .trex files into the ~\Tableau Repository\Extensions directory?

**Comment by d45** [comment]
@datocrats-org  - sounds like your npm server was running correctly.  You are looking at the index.html landing page. The Extension samples are running in the folders under Samples and Tutorial and should appear when you drag them on to the dashboard, provided the `.trex` files are in the **Tableau Repository( Beta)\Extensions** folder.  
I don't want to make you run around... but you might want to switch to the latest Tableau Developer Preview release (https://prerelease.tableau.com) and download or clone the latest version of master. In the latest 0.8 release, you no longer have to place the `.trex` files in the **Tableau Repository( Beta)\Extensions** directory. You can browse for them.  
Also, you might try looking at the log files to see if the `.trex` files are getting parsed correctly.  See [Using Log files..](https://tableau.github.io/extensions-api/docs/trex_logging.html)

**Comment by KeshiaRose** [comment]
Closing this as it's been over a year and we've officially released extensions since then. If you are still seeing this issue with our current release please re-open!
