### ISSUE TITLE
How to relate data to the corresponding fields if forecasting exists?

### ISSUE THREAD

**Issue by adrianasg122** [tableau/extensions-api#330]
Hi everyone.

We're experiencing some problems using the API with worksheets that have the forecast model.
When we receive the data from Tableau, we have records with several values for the same field, but we need to relate that data to the corresponding field, by being able to distinguish the datasource data from the forecast data and at the moment it seems that there is no information available that would enable us to make that distinction. Is there any way around this problem?

We are experiencing this issue developing Write-back.

**Comment by Kovner** [comment]
I assume you're using Tableau's built-in forecasting? If so, Tableau also generates a Dimension that indicates if a row is generated or not. That should be in the getData call.
