### ISSUE TITLE
More so question than issue (sanboxed extensions)

### ISSUE THREAD

**Issue by abelbarrera15** [tableau/extensions-api#331]
I'm in the process of deciding if to buy tableau/set-up a server, but I need to know if the tableau sandox extensions are configurable to read from the data that is pre-poured into the tableau workbook/dashboard/(whatever the word is) itself? 

This is because I need to apply row-level security on the data the sandboxed extension is manipulating, but I know I cannot do this natively through tableau unless the extension itself is able to read the data from the tableau server import of data as opposed to the DB it is from itself.

Would appreciate any documentation/feed back. Thank you

**Comment by Kovner** [comment]
I don't fully understand the use case, but in general, any filtering you do with the Extensions API would not be secure. The user could un-do the filter. Therefore, it's not a good idea to use Extensions for filters that need to be secure.

To answer your specific question, though: Sandboxed Extensions can read the 'underlying' (database/row-level data) or the 'Summary' data (aggregated data that the user is seeing).
https://tableau.github.io/extensions-api/docs/interfaces/worksheet.html#getsummarydataasync
https://tableau.github.io/extensions-api/docs/interfaces/worksheet.html#getunderlyingtabledataasync

I hope that helps!

**Comment by abelbarrera15** [comment]
This makes sense-- before I mark this as resolved @Kovner -- one more question. Say the tableau underlying data is using RLS (row level security) locked down to the user-- would either one of those api methods respect the RLS as if the call was being made by the user? Or no?

**Comment by Kovner** [comment]
Yep, all queries from the API would respect the RLS that has been built into the dashboard or datasource.

**Comment by abelbarrera15** [comment]
Thank you! Much appreciated
