### ISSUE TITLE
identify hidden sheets in dashboard

### ISSUE THREAD

**Issue by aksharj** [tableau/extensions-api#332]
Hi All,

I am trying to allow the users to export data from sheets which we have in a dashboard. The export part works fine.

Currently the user sees all the sheet names to export from, some of which are hidden and do not have any data.

Is there a way to identify hidden sheets / sheets with dimension of 1px, so that these sheets are not shown to the user when exporting data from.

Any help in this would be really great. Thanks.

**Comment by Kovner** [comment]
You mentioned two ways a worksheet can be hidden: It can have all of its data filtered out so it isn't displaying anything. The only way to know that is to query getSummaryData and check for the size of the returned table.
The other way is that you have a sheet with just 1px x 1px (or something similar). You can find that out by querying the size property of the Worksheet object.

Hope that helps!

**Comment by Kovner** [comment]
Oh and there's one more way a Worksheet can be hidden: With the show/hide functionality that the Button objects can do, or using the Extension API's setZoneVisibility functionality (which does the same thing as show/hide via Button).
You can query if a Dashboard Object is hidden in that manner with 
https://tableau.github.io/extensions-api/docs/interfaces/dashboardobject.html#isvisible

**Comment by aksharj** [comment]
Hello @Kovner, many thanks for your reply, this is definitely helpfull.
