### ISSUE TITLE
Idea - Event hooks for various dashboard operations

### ISSUE THREAD

**Issue by dhwanils95** [tableau/extensions-api#333]
Hello,

Can we have various events that can be triggered on different dashboard level operations such as whenever a sheet is removed from the dashboard, or the current extension is closed/deleted? My use case is, the extension that I am trying to build is linked to a Sheet of the user's choice and if the sheet is removed from the Dashboard or if the fields used in that sheet changed, I should get a callback to ensure I can reflect the changes without taking the overhead to check for changes manually.

The biggest requirement would be to be able to access the state of the extension's own state, like when it is removed from the Dashboard. I tried to use the DOM's `unload and beforeunload` event listeners on the window and the parent of the window (Since the extension is embedded in an iframe) but none get triggered. This would help us make a clean-up API call to update something like let's say usage. 
Which brings me to the next and final requirement, can we have some way to identify the user via some ID or session ID? I need to license my plugin to ensure it complies to our FUP (Fair Usage Policy) but I am unable to do that since I cannot who is viewing the extension right now. Since the dashboards are shared instances across users, I cannot correctly track how many users are viewing my extension.

If there is any way to do this right now, please let me know or are these feasible or if this is intentionally left out, can you brief about that?

Thanks in advance.

**Comment by bcantoni** [comment]
Parts of the original request here have been included as part of [Extensions API Release 1.7](https://tableau.github.io/extensions-api/docs/trex_release-notes.html#tableau-dashboard-extensions-api-version-17) where several new event types are now available.
