### ISSUE TITLE
2020.2 summaryDataAsync returns 10k rows

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#334]
Dear Tableau,

We just found a major issue with Tableau 2020.2 and extensions.
It appears that the getSummaryDataAsync is only returning 10k rows instead of the full summary data.
This wasn't happening in previous versions and we can't control this behavior if I look at the GetSummaryDataOptions.

Can you please report back to us asap? We have customers who have upgraded and have major data issues with SuperTables and other extensions.

**Comment by SiebeG** [comment]
We have a client using over 7M rows ending up with only 10K of rows in the extension.

**Comment by Kovner** [comment]
Hi yes this is a known issue. The fix is all but done and will be in the next Maintenance Release of 2020.2.

**Comment by SiebeG** [comment]
@Kovner is there an estimate on when the maintenance release will be released? We have a lot of customers complaining on the 10K limit in Tableau 2020.2

So we really hope this will be released very soon.

**Comment by Kovner** [comment]
@SiebeG @merlijnbuit,
I checked in with the team. The fix is scheduled to be 'checked in' this week, but we missed the train for the June Maintenance Release, so it will be in the July Maintenance Release. I know this is a pain. I'm sorry!

**Comment by demartsc** [comment]
Glad this is getting addressed @Kovner as it is also a big issue for users of the kepler.gl extension.

**Comment by Kovner** [comment]
@SiebeG does your client really have 7m rows from getSummaryData or is the 7m rows at the underlying data level?

**Comment by SiebeG** [comment]
@Kovner, The client is actually trying to feed 7M rows to the extension. In most use cases this might not be best practice and we advise to filter or aggregate the data before feeding it to the extension.

Using large amounts of records often triggers the Extensions API to time out. Might also be a great feature to allow paged loading or incremental loading through the Extensions API to provide large numbers of records to the extensions.

**Comment by GuillaumeDataMa** [comment]
Same here. Thanks for the fix and letting me know when done. Thanks!

**Comment by SiebeG** [comment]
@Kovner what is the reason that getSummaryDataAsync is now limited in number of rows? In previous versions of Tableau there was no limit on getSummaryDataAsync

**Comment by johnDance** [comment]
@SiebeG - The underlying implementation for getSummaryDataAsync was changed as part of the introduction to the new Object Model in Tableau. (If you haven't explored the new Object Model, it will be awesome in simplifying your data analysis.) Anyway, the new Object Model implementation had a limit on the results we use for getSummaryDataAsync without our team being aware. This has been fixed and will be part of the maintenance release in July. I believe that will be 2020.2.3. 
John

**Comment by craigbloodworth** [comment]
I've tested this with 2020.2.4 and the 10k record limit no longer exists

**Comment by JD-Franco** [comment]
I am experiencing a significant performance decline to the point where if the dataset is bigger than a couple thousand rows the extension freezes and takes minutes to load data into a simple HTML table. Does anyone else have the same issue on 2020.2.4?

**Comment by bcantoni** [comment]
Closing as fixed.
