### ISSUE TITLE
Extensions API still behaving different on Tableau Server and Desktop

### ISSUE THREAD

**Issue by SiebeG** [tableau/extensions-api#335]
Hi @johnDance  / DevTeam

You may have to re-open ticket/issue 143 since Tableau Server (Tableau Online) does not register the dashboard action when you use the GoTo Dashboard action before it redirects to the new dashboard/sheet. We store the event of the dashboard action but it never gets stored because the GoTo action will have the user leave the dashboard and the extension does not get the important event of the dashboard action.

I can confirm it works in Tableau Desktop (2019.3 and higher) but on tableau Server the registration of the selection doe snot take place. I tested in all versions up to 2020.2 (Tableau Online) and i cannot get the dashboard action to be registered before the GoTo sheet/dashboard action will redirect to the new dashboard/sheet.

**This is an urgent issue for us since one of our clients has indicated not to continue their subscription on the extension if this will not be fixed.**

_Originally posted by @SiebeG in https://github.com/tableau/extensions-api/issues/143#issuecomment-644242407_

**Comment by johnDance** [comment]
Hi @SiebeG 
Sorry for the delay. I was out of the office. Just to confirm... you register for selection events. You have a selection action that is a GoTo Sheet action. When you make the selection, the GoTo Sheet action fires before the extension gets notified of the selection. Do I have your scenario correct? What type of work is the extension doing as part of the selection notification?

Please confirm, and we will look into the issue.

Thank you,
John

**Comment by johnDance** [comment]
For discussion and follow-up, let's use: https://github.com/tableau/extensions-api/issues/235.
That has a little more context. Thank you.

**Comment by bcantoni** [comment]
Conversation is happening in #235 so we can close this one.
