### ISSUE TITLE
Bug getSummaryData with no data in worksheet/datasource

### ISSUE THREAD

**Issue by yoramdelangen** [tableau/extensions-api#337]
When having a worksheet with no records and the extensions is trying to load the summary data it will fail with the following error: 
![Screenshot 2020-06-29 at 08 45 14](https://user-images.githubusercontent.com/1531885/85982101-8f3cd780-b9e5-11ea-8363-0dd898051715.png)

Quick way to reproduce it, is create a empty database or csv and load it in as data source.

**Comment by johnDance** [comment]
Hi Yoram
What version of Tableau are you using? This issue was present in Desktop/Server 2020.2, but should have been fixed in 2020.2.2+.
John

**Comment by yoramdelangen** [comment]
Indeed its fixed in the latest version :-) Thank you
