### ISSUE TITLE
Unable to download data having size more that 20mb on IE11

### ISSUE THREAD

**Issue by DataPalla** [tableau/extensions-api#338]
Team, 
Good Morning/Evening ! 
I am using Trusted authentication for my users to  get authenticated, when my users are trying to download data using the Export all Extension(over 20mb file) on IE11, it spins for 2~3 minutes(wont download)and tries to refresh the page with same URL string (throwing an error "Could not locate unexpired trusted ticket error". Would someone please help me if there is way to tweak the code for the application to download larger files on IE.
Thanking you in anticipation.

Please.. Please

**Comment by bcantoni** [comment]
Closing out - this would actually be a support question for the authors of the Export All extension.
