### ISSUE TITLE
Different mark selections return different data from API

### ISSUE THREAD

**Issue by lcsixp** [tableau/extensions-api#342]
Hey all,

We faced a problem where selecting a mark from visualization in two different ways, retrieved different data from the getSUmmaryDataAsync() and getSelectedMarksAsync(), one of them being a little misleading. Not sure if related, but this happened when we had measures (like Date) in the worksheet Detail.

This is a screenshot of the visualization where we tested this:
![image](https://user-images.githubusercontent.com/57663873/89044775-55dbec80-d342-11ea-8b13-a01117356558.png)

When we simply left mouse click on the Finland mark and then perform the API calls mentioned above this is the data that gets retrieved (only one record, the record chosen is also not consistent):
![image](https://user-images.githubusercontent.com/57663873/89044906-86238b00-d342-11ea-885d-e762972d768d.png)

However, when we use one of the selection options available here:
![image](https://user-images.githubusercontent.com/57663873/89045000-ae12ee80-d342-11ea-8b20-0416686eb2e1.png)
to select Finland (click, drag and drop) the results from the API are very different:
![image](https://user-images.githubusercontent.com/57663873/89045051-c420af00-d342-11ea-91e5-cd435afc27e9.png)

This behaviour does not seem consistent and in our use case ([Write-Back](https://extensiongallery.tableau.com/extensions/114?version=2019.4&per-page=50)), if a user was to insert a record for the SUM(Profit) of Finland and performed a simple left-click on the mark, the comment would not be correctly related the SUM(Profit) of Finland, but to a small part of it (specific to the dimensions on the details, in the example just one Month).

Is there any difference between the selections that we should have expected? Is there a way to always retrieve all the data for the mark regarding the selection event we just described?  

Would really appreciate your help,

Sincerely,
Luciano,
Write-Back Team

**Comment by demartsc** [comment]
@lcsixp - it looks to me like you have two data points layered on Finland. When you click on Finland, you only get one, when you use the selector you get both. This seems like expected behavior to me. Can you confirm whether Tableau shows 1 or 2 marks selected in Tableau Desktop on each of your cases above?

**Comment by lcsixp** [comment]
@demartsc 

Hey,

Thanks for the response, I am not sure what you mean by two data points layered on Finland, but for instance, this does not seem very consistent.

Here I single click Finland, and it shows 1 mark selected 
![image](https://user-images.githubusercontent.com/57663873/89055424-3fd62800-d352-11ea-8142-997726de7301.png)

When I click, drag and drop the selection on Finland it shows 11 marks selected 
![image](https://user-images.githubusercontent.com/57663873/89055468-554b5200-d352-11ea-823d-e8560bd43bb3.png)

I'm just really confused about why it isn't 11 marks for both types of selection.

Thanks a lot,
Sincerely,
Luciano
Write-Back Team

**Comment by demartsc** [comment]
@lcsixp if you take Month(Order Date) off the detail shelf I would expect these two actions to be consistent. But the way your sheet is set up, the clock is returning the “top” copy of data on Finland and the selection is returning “all” copies of data on Finland. 

I would expect the API to return marks which match that count in Tableau Desktop. If Desktop says 11 and the API is only returning 2 that would be an off behavior to me.

**Comment by johnDance** [comment]
@lcsixp  The comments by @demartsc are spot on. A click will only select a single item in a worksheet. It will select the topmost mark when there is overlap of any kind. A click+drag, or region select will select all marks that intersect the selection. The API should match the number of items selected as listed in the information bar. 
John

**Comment by lcsixp** [comment]
Hey @johnDance @demartsc,

I believe the API is working as intended since it is retrieving the amount of information that matches the amount of marks Tableau Desktop indicates. However, it really bothers me that the both selections will not select the same amount of marks. I opened a similar question on Tableau Desktop forum, just to understand why this choice.

In the meantime, we are documenting this behavior in our documentation and will inform customers when trying to enter data for a mark.

Thanks

**Comment by demartsc** [comment]
Fair enough, not sure there is a use case for layering 12 marks on top of each other and allowing the user to click on things they can’t see. In the example you provided you need to remove date from the detail shelf. Having this added keeps your viz from aggregating across the year... Either way though, I do think we identified that this is more a Desktop thing than an extensions API thing. Probably can close this item @lcsixp

**Comment by lcsixp** [comment]
@demartsc Yeah, thank you so much. I am closing the issue :)
