### ISSUE TITLE
Settings are not persisted on Tableau Server

### ISSUE THREAD

**Issue by TomNes94** [tableau/extensions-api#345]
Hello,

I'm trying to incorporate the settings API into my extensions. The result is not quite what I expected based on the documentation. In Tableau Desktop, saving a setting saves the setting in the Workbook. Closing and opening the Workbook does not remove the settings. On Tableau Server, saved settings do not seem to persist. When I press F5, the settings are not deleted. However, closing and reopening the browser tab seems to delete the saved settings. The code I use is barebones:
The saving:
```
 await tableau.extensions.initializeAsync();
 tableau.extensions.settings.set("comment", newComment);
 await tableau.extensions.settings.saveAsync();
```
The logging (on page load):
``` 
 await tableau.extensions.initializeAsync();
 console.log(tableau.extensions.settings.getAll());
```

Do I misunderstand the documentation? Or should the settings be persisted over browser sessions?

**Comment by Kovner** [comment]
This is as expected: You can only save the settings to the workbook in Authoring mode, not in view mode.

**Comment by TomNes94** [comment]
Alright, I see. Thanks for clearing that up
