### ISSUE TITLE
Handling Column Referencing & Duplicate Column Names in Summary Data

### ISSUE THREAD

**Issue by craigbloodworth** [tableau/extensions-api#349]
I'm interested to know how folks handle column referencing in summary data especially when it comes to columns that have the same fieldName property.

For instance a quick table calc will appear to be the same fieldName as a duplicate, non table calc aggregate:
![image](https://user-images.githubusercontent.com/8116300/91547332-a9c6fa80-e91b-11ea-8f78-597e49cc69e3.png)

While I considered using the index field to differentiate between the two it isn't reliable as it will change based on the user modifying the order of fields in the sheet. Why doesn't the SDK provide the unique field reference present in the twb XML? This would surely sort out the issue?

Currently my users get strange behaviour from the extension as depending on the field ordering & extension configuration they get unexplained results all caused by duplicate field names.

**Comment by johnDance** [comment]
We made an unfortunate decision to use the name rather than the field Id (as you suggest). We are looking at how to incorporate the field id without adding a completely new API.

**Comment by craigbloodworth** [comment]
Thanks for the update @johnDance, yes this seems to have been a bit short sighted as it affects multiple language use. If you configure an extension in English aggregates have the field name SUM ( ) or AVG ( ) however when a user with for instance Japanese set as their local language the field name changes from AVG ( ) to 平均 ( )

Unless you can provide a giant lookup table for all possible aggregations & languages extensions are broken for anybody in this situation.

**Comment by johnDance** [comment]
Agreed, and sad. We will be fixing this. I just don't know the time frame yet.

**Comment by bcantoni** [comment]
Closing this as a won't fix in a general sense, but starting with [Extensions API release 1.5](https://tableau.github.io/extensions-api/docs/trex_release-notes.html#tableau-dashboard-extensions-api-version-15), the field ID is now returned along with the field name, so that may be helpful here.
