### ISSUE TITLE
Very small typo in docs

### ISSUE THREAD

**Issue by geordielad** [tableau/extensions-api#35]
https://tableau.github.io/extensions-api/docs/interfaces/analyticsobject.html

"An **anlytics** object is abstract class representing an analytics object in a worksheet. Currently, this is limitted to trend line, forecast, and cluster objects."

**Comment by lbrendanl** [comment]
Thanks @geordielad, good catch.

I've fixed this in one of our development branches so this will be fixed on the website shortly.
