### ISSUE TITLE
Disable manual resizing of the dialog

### ISSUE THREAD

**Issue by melquic** [tableau/extensions-api#361]
Hi guys,
It would be great if we could disable the resizing of the dialog window, thus preventing the user from resizing it manually.
Something like:
`tableau.extensions.ui.displayDialogAsync(popupUrl, data, {
            height: 500,
            width: 500,
            resizable: false
        })`

Please let me know if there is any workaround for that today.
Thanks.

**Comment by bcantoni** [comment]
@melquic could you give more context here - is there a specific problem you're encountering when users resize manually?

**Comment by melquic** [comment]
@bcantoni the problem is not with the resize itself. The problem is that in Windows the dialog box is always showing a scrollbar, even without content to scroll, which ends up suggesting to the user to resize it. This does not happen on the Mac.

**Comment by johnDance** [comment]
@melquic - We are currently working on displayDialogAsync. We will respect the size passed in, and make it non-resizable. 
Thanks.

**Comment by johnDance** [comment]
See the new DialogStyle.Modal - https://tableau.github.io/extensions-api/docs/enums/tableau.dialogstyle.html#modal
