### ISSUE TITLE
Trigger and populate the native Tooltip from within an extension

### ISSUE THREAD

**Issue by abusedmedia** [tableau/extensions-api#364]
Since it's a global object not scoped within a worksheet, I guess there's room for feasibility.
Is it possibile or planned to be implemented in the API?
Best

**Comment by johnDance** [comment]
Hi
We don't have this currently planned, but we are always open to new ideas on extension APIs. Normally, the tooltip will show when you hover over a mark, and contains mark specific data. Adding to that content is an interesting idea. Could you share more about when you would want to trigger the tooltip from an extension? Is it really a mark tooltip that you want to trigger? Tell us more. 
Thanks
John
