### ISSUE TITLE
Not able to input character that require ALT GR in most recent versions of Tableau Desktop. Seems to be affecting all extensions.

### ISSUE THREAD

**Issue by bggoxp** [tableau/extensions-api#371]
Hi again,

This time around, with the most recent versions of Tableau Desktop, I found out that it is no longer possible to input characters that require the ALT GR key, such as @ and { [ ] }.
I tried a few extensions and saw the behaviour happening on all of them.

I've also uploaded a video about this issue, here:
https://youtu.be/59jcwQReKUE

If I copy and paste, the characters show up, only when I try to input them they don't show up.

Are you aware of this issue and do you know of any solution for it?

Thank you.

**Comment by KeshiaRose** [comment]
Hi Bruno, it looks like this is another bug brought on from the update to Qt WebEngine 5.15.0. 🙁  It seems that the Qt team has [already fixed this bug in 5.15.1](https://bugreports.qt.io/browse/QTBUG-83710) and I've opened up a ticket to get this version backported to maintenance versions of Tableau but I don't have a date for when it will get in, unfortunately.
-Keshia

_Internal: 1244613_

**Comment by bggoxp** [comment]
Hi Keshia,

Thank you very much for the update! 

We'll be on the lookout for the release notes for the maintenance versions, but if happen to get a more concrete date do let us know.

Thank you,
Bruno
