### ISSUE TITLE
filter method getFieldAsync does return 401 on super store example

### ISSUE THREAD

**Issue by LingVuDev** [tableau/extensions-api#376]
### Description
I have faced an issue where I wanted to get the field that was used for a filter. For this I found in the API reference this method [getFieldAsync()](https://tableau.github.io/extensions-api/docs/interfaces/filter.html#getfieldasync). But instead of returning the field object, I always get unauthorized response, even though everything else from the API does work.

### What I am using
Workbook: SuperStore - Shipping

### My implementation
```ts
export async function getColumnRoles(worksheet: Worksheet): void {
  let metaInfo: any = {};
  const filters = await worksheet.getFiltersAsync();
  console.log(filters);
  // This gives me the error 
  console.log(await filters[0].getFieldAsync());
}
```

### Request (simplified)
```
Request URL: [...]/w/Superstore/v/Shipping/sessions/A3093F7D1A1D4B409E9D8146FC983557-0:0/commands/tabdoc/get-datasource-pres-model
Request Method: POST
Status Code: 401 
Remote Address: [...]
Referrer Policy: strict-origin-when-cross-origin
```
My goal in the end is to find out whether the filter is assigned to a field which is a dimension or measure

**Comment by johnDance** [comment]
Hello @LingVuDev 
We have recently found and fixed an issue with Filter.getFieldAsync(). It will be fixed in our upcoming 1.5 version of the extension library (coming in Q2).  Meanwhile, the only work-around would be to use Filter.fieldId, and look up the field in DataSource.fields. From that field, you can get the role. 
John

**Comment by LingVuDev** [comment]
Still getting a `401` on the latest extension version `1.5.0`. I am using exactly this code snippet:
```js
const worksheets = await tableau.extensions.dashboardContent.dashboard.worksheets.forEach(
    async (worksheet: Worksheet) => {
      const filters = await worksheet.getFiltersAsync();
      filters.forEach(async (filter) => {
        const field = await filter.getFieldAsync();
        console.log(field);
      })
    },
  );
```

**Comment by LingVuDev** [comment]
<img width="1468" alt="Screenshot 2021-06-17 at 09 32 35" src="https://user-images.githubusercontent.com/30183724/122352611-8f641900-cf4f-11eb-9585-16017055f34d.png">

**Comment by LingVuDev** [comment]
Still getting a `401` on the latest extension version `1.5.0`. I am using exactly this code snippet:
```js
const worksheets = await tableau.extensions.dashboardContent.dashboard.worksheets.forEach(
    async (worksheet: Worksheet) => {
      const filters = await worksheet.getFiltersAsync();
      filters.forEach(async (filter) => {
        const field = await filter.getFieldAsync();
        console.log(field);
      })
    },
  );
```
<img width="1468" alt="Screenshot 2021-06-17 at 09 32 35" src="https://user-images.githubusercontent.com/30183724/122352611-8f641900-cf4f-11eb-9585-16017055f34d.png">

**Comment by jcognard-actinvision** [comment]
Hello,

I have the same issue and I cannot use your workaround @johnDance because what I want is to retrieve the datasource from the field object.
Indeed, using Worksheet.getDatasourcesAsync() is way too long to execute when I just want to retrieve one precise datasource name.

**Comment by johnDance** [comment]
@LingVuDev 
I am sorry for the delay. We converted to a new mail client, and messages got buried.

We have duplicated the issue on server. It will be fixed in the October maintenance releases of Tableau server.

Thanks for your patience.
John

**Comment by johnDance** [comment]
@LingVuDev 
Actually... September maintenance releases. It should be fixed in 2020.4.9, 2021.1.6, 2021.2.3, 2021.3.1
Thanks again,
John

**Comment by johnDance** [comment]
There was a security update to 2021.3, so the maintenance releases that this is fix in are now:
2020.4.9, 2021.1.6, 2021.2.3, 2021.3.2, and online

**Comment by bcantoni** [comment]
Closing as fixed.
