### ISSUE TITLE
Getting columns of a `DataTable` changes field name when user locale settings changes

### ISSUE THREAD

**Issue by LingVuDev** [tableau/extensions-api#383]
### Background

I was starting to fetch the data from a worksheet (widget) based on the available worksheets on the dashboard. From that I tried to extract the columns used by the worksheet. After that I have the `columns`. Now the problem is, that the naming of certain filter options are translated based on the local settings which also influences the column naming. The column itself has no id which I can relate to. This name change causes some issues for me, but I couldn't find any documentation of the different naming for that:

Images of my developed application
**EN:**
![image-en](https://user-images.githubusercontent.com/30183724/118772066-98e05f80-b883-11eb-8910-e302474780f5.jpg)

**DE:**
![image-de](https://user-images.githubusercontent.com/30183724/118772072-9a118c80-b883-11eb-9a03-92dbabadc4f2.jpg)

(Example from the Super Store - Shipping Dashboard)

* Documentation for date functions in German: https://help.tableau.com/current/pro/desktop/de-de/functions_functions_date.htm
* Documentation for date functions in English: https://help.tableau.com/current/pro/desktop/en-us/functions_functions_date.htm

The documentation clearly shows the filter functions for both language the same naming (at least for date functions)

### Reproduce the issue
1. Depending on the region set the language to **DE**:
  * User Settings -> Users -> Settings -> Language
  * <img width="877" alt="Screenshot 2021-05-19 at 09 33 26" src="https://user-images.githubusercontent.com/30183724/118773873-823b0800-b885-11eb-8026-280dbdc8746a.png">

2. Get all available worksheets:
```
const worksheets = tableau?.extensions.dashboardContent?.dashboard.worksheets;
```

3. Extract the summary data from it:
```
const worksheet = worksheets.find(worksheet => ...);
const summaryData = await worksheet.getSummaryDataAsync();
```
4. Getting the columns from it:
```
const columns = summaryData.columns;
```
5. For example, the data looks like this (simplified):
```
[
  {
    "_fieldName": "ANZ(Orders)", // <--- in EN this is CNT
    "_dataType": "float",
    "_isReferenced": true,
    "_index": 1
  }
]
```

### Expectation
This issue can be solved in 3 ways:
* You provide a documentation where I have all available action functions (translated) for the each language 
* You change the api so that the language setting does not influence the naming of the column [fieldName](https://tableau.github.io/extensions-api/docs/interfaces/column.html#fieldname)
* Or you provide a unique identifier for column (which is probably not favorable, because of the api type change)

**Comment by johnDance** [comment]
@LingVuDev : You will be happy to know that in Tableau 2021.2, we have added fieldIds to the column information. When getting Summary or Underlying data, you can filter with columnsToInclude and now columnsToIncludeById. Tableau 2021.2 will be released soon.

Your example column will now have the following:
{
fieldName: "CNT(Orders)",
fieldId: "[federated.10nnk8d1vgmw8q17yu76u06pnbcj].[cnt:Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9:qk]",
dataType: "int",
isReferenced: true,
index: 1
}

There are other places in the API where we need to allow the id rather than just the name. Those changes will be coming in future releases.
Thanks,
John

**Comment by LingVuDev** [comment]
@johnDance Sorry for the late response. This feature works perfectly. I used the `id` to reference each field, so I can actively prevent name changes when the locale changes. 

I will close this ticket.
