### ISSUE TITLE
Getting `undefined` when trying to access the `fieldId` of a column

### ISSUE THREAD

**Issue by LingVuDev** [tableau/extensions-api#388]
### Description

With the announcement of `1.5.0` it should be possible to retrieve the `fieldId` from a column. I was immediately trying it on my extension with the `Superstore - Shipping` dashboard. Unfortunately I couldn't see any changes in the response of the API. Still getting the same reponse without the `fieldId`.

Used:
* Macbook Pro 15" Late 2015 - Big Sur 11.2.3
* Chrome (latest) Version 91.0.4472.77 (Official Build) (x86_64)

### Steps to reproduce
1. Updated the extension api to `1.5.0`
2. Get the first worksheet `tableau.extensions.dashboardContent.dashboard.worksheets[0]` 
3. Get the summaryData from it `worksheet.getSummaryDataAsync()`
4. I use this summaryData to get the columns `summaryData.columns`

None of them contained an `fieldId`, it looks like this:
```
{"_fieldName":"CNT(Orders)","_dataType":"float","_isReferenced":true,"_index":1}
```

**Comment by johnDance** [comment]
Hello @LingVuDev 

Thanks for trying it out so quickly. It appears that you are still using a previous version of the extension api. I would suggest dumping the Environment to the console, and then also the DataTable from getSummaryDataAsync.

Here is what I get when running against Tableau desktop. I put a breakpoint after getSummaryDataAsync, and then did the following in the console:

![image](https://user-images.githubusercontent.com/37640168/121435482-d3459580-c933-11eb-81aa-1463cb627e62.png)

**Comment by LingVuDev** [comment]
Oh yes, I did some investigation and you were totally right. Somehow, my script doesn't replace it. So my bad. But thanks for the fast response. Really apprechiate your support.
