### ISSUE TITLE
Case sensitivity in Samples folder names

### ISSUE THREAD

**Issue by geordielad** [tableau/extensions-api#39]
On a Windows PC running the samples in Node does not cause a problem but if the samples are run on Linux (or Docker) then the trex file uses a lowercase case path to the samples while the folders themselves have uppercase. This means that the folders do not match. I am surprised this did not show up for Mac users - so I might be missing something.

**Comment by tfoldi** [comment]
Just for the record: Mac file/folder names are not case sensitive. Maybe no one checked on Linux I guess :)

**Comment by lbrendanl** [comment]
Thanks @geordielad, I fixed this in dev so should be set when that change makes it to the master branch.
