### ISSUE TITLE
Clarifications about tableau.extensions.dashboard.worksheets

### ISSUE THREAD

**Issue by adrianasg122** [tableau/extensions-api#391]
Good afternoon.

I am creating this topic as a way to try to understand some inconsistencies that I am experiencing using the Tableau Extensions API by using tableau.extensions.dashboard.worksheets objects.

In our use case, we use that objects to add event listeners to the worksheets, by using the addEventListener method.  What happens is that after renaming a worksheet I can't get the list of updated worksheets, but if I open a popup window I can get the correct result. The same happens if I reload the extension. After the reload, the result I get is correct. Is there an explanation for this? It is something that we have started to experience recently.

**Comment by bcantoni** [comment]
I'm going to close this one out, but @adrianasg122 if you are still experiencing this issue please feel free to reopen with a comment and we can revisit.
