### ISSUE TITLE
applyFilterAsync throws error when applying values for Measure Names filter

### ISSUE THREAD

**Issue by bartoszZamojcinRoche** [tableau/extensions-api#444]
Hello,

While applying Measure Names filter using applyFilterAsync method of Worksheet object Extensions API throws following internal error:
![image](https://user-images.githubusercontent.com/96522947/147084185-1b22586b-9a84-42d8-b558-fc5a268516ec.png)

Bartosz

**Comment by johnDance** [comment]
Hi @bartoszZamojcin 

This is actually a duplicate of https://github.com/tableau/extensions-api/issues/443. As the filter does its work, it uses the same selection implementation. Fixing that issue will also fix this issue.

Thanks,
John

**Comment by johnDance** [comment]
Internal defect #1372577 (same as https://github.com/tableau/extensions-api/issues/443)

**Comment by johnDance** [comment]
Hi @bartoszZamojcinRoche 
Like #443, has also been fixed in 2022.2. 
Thanks,
John
