### ISSUE TITLE
applyFilterAsync creates new filter with the same name instead of applying existing one

### ISSUE THREAD

**Issue by bartoszZamojcinRoche** [tableau/extensions-api#445]
Hello,

While applying YEAR(Order Date) filter in Superstore Customers dashboard using applyFilterAsync method of Worksheet object new filter with the same name is created instead of applying values to existing one.
![image](https://user-images.githubusercontent.com/96522947/147087007-36f64a5c-c419-4070-ad62-abd9d456d611.png)

Bartosz

**Comment by johnDance** [comment]
Hi @bartoszZamojcin 
Good news here. This has been fixed in 2021.4.3. I was able to reproduce the problem in 2021.3, but it works in 2021.4.3.
John

**Comment by bartoszZamojcinRoche** [comment]
Hello @johnDance 
good to hear it, but currently we are limited to version 2021.1.4 and problem still exists. We would appreciate it if you can propose any workaround how to apply original filter, as our internal investigation leads us nowhere.

Bartosz

**Comment by johnDance** [comment]
@bartoszZamojcinRoche 
Would you be able to update to 2021.1.n? If so, we can see if we could backport the change. If not, we'll have to get with the filter team to see if there is some way to combine the filters.
Let us know.
Thank you,
John

**Comment by bartoszZamojcinRoche** [comment]
@johnDance 
We already use version 2021.1.4 so if you could backport the solution and deal with the issue that way it will be great.

Bartosz

**Comment by johnDance** [comment]
Filter team is unable to backport to 2021.1. Sorry.
