### ISSUE TITLE
Artifactory down - impossible to install

### ISSUE THREAD

**Issue by ihrimech** [tableau/extensions-api#456]
**Description :**
After trying to `npm install` the project, it seems that the registry used isn't reachable.

**Version information:**
 - Tableau  extension version: 1.8.0 (but that seems independant from the version
 - OS: MacOS (don't think it's relevant anyway)

**Steps to reproduce :**
1. clean local `npm packages` so it gets loaded again
2. clone this repository
3. run npm install
 
> npm ERR! code ETIMEDOUT
> npm ERR! syscall connect
> npm ERR! errno ETIMEDOUT
> npm ERR! network request to https://artifactory.prod.tableautools.com/artifactory/api/npm/tab-npm/@xtuc/long/-/long-4.2.2.tgz failed, reason: connect ETIMEDOUT 10.26.131.15:443
> npm ERR! network This is a problem related to network connectivity.
> npm ERR! network In most cases you are behind a proxy or have bad network settings.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/9653433/149965007-0657010b-5cc3-4e70-b5f6-a07827146a85.png">

**Comment by elbandito** [comment]
@ihrimech thanks for taking the time to submit this issue.  Are you still seeing this?  I just now tried running `npm install` against the `main` branch and I wasn't able to reproduce this.

**Comment by ihrimech** [comment]
Hello, and thanks for the quick response ! 
Unfortunatly, I'm still having the issue. And i'm pretty sure I'm not behind a proxy.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/9653433/150095416-4998ab8d-080e-4860-b4f2-d2c9537988a5.png">
<img width="533" alt="image" src="https://user-images.githubusercontent.com/9653433/150095619-26946296-fe6b-4516-9f5d-dff9f80ada18.png">

**Comment by seanmakesgames** [comment]
Hey @ihrimech !

Sorry about this. A workaround for this is to delete the `package-lock.json` file and run `npm install` again.

Let us know how that goes!

**Comment by ihrimech** [comment]
Works perfectly well thanks !
