### ISSUE TITLE
Consider removing Community Portal from docs

### ISSUE THREAD

**Issue by bcantoni** [tableau/extensions-api#463]
The [Community Portal](https://tableau.github.io/extensions-api/community/) lists a couple dozen extensions written by the community. We should consider removing it because it hasn't been updated recently (last addition July 2020) and it has largely been replaced by <https://exchange.tableau.com>.

These are the places which require change:
* modify nav head (_includes/header.html)
* remove layout (_layouts/community.html)
* remove community section (community/)
* modify home page (index.html)

**Comment by johnDance** [comment]
Are there actions we could take to juice up the community portal? Without any links, it will die a slow and painful death.

**Comment by bcantoni** [comment]
Well if we implemented the change suggested here, it would die right away because we'd be removing it. I'm just suggesting the idea but happy to hear reasons why we should keep it.

**Comment by bcantoni** [comment]
Further conversations with the team clarified: these extensions still have a place as "community" level contributions as opposed to the more formal/vetted extensions in Tableau Exchange. It's still true it hasn't been updated in quite a while, but there's no urgency to remove it.
