### ISSUE TITLE
Permission mismatch on Tableau Server/Online 

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#479]
Users using extensions on Tableau Server need the 'Download Summarydata' permission. If this permission is not enabled the extension won't run and throw an unexpected error in the developer tool console.

A clear and concise description of what the issue is.

**Version information:**
 - Tableau version: 2021.4
 - OS: -
 - Browser: All
 - Version All

**Steps to reproduce (please include a code snippet, if possible):**
1. Have a user denied 'Download summarydata' permissions
2. Go to Tableau Server and open a workbook with SuperTables with this user
3. See the error in the console of the developer tools

A clear and concise description of what you expected to happen:
<img width="1247" alt="errors" src="https://user-images.githubusercontent.com/16118919/155716420-c0d58667-cc10-437b-8609-993d2874dd01.png">

**Comment by johnDance** [comment]
Hi Merlijn
Thank you for reporting this. We will investigate how we can improve the error handling.
John

**Comment by johnDance** [comment]
As we discussed off-line, "download summary data" permission is required for getting the summary data and getting the parameters. We have discussed work-arounds with our security team, but have not had any success. 
John
