### ISSUE TITLE
Proposal:  Versioning

### ISSUE THREAD

**Issue by benlower** [tableau/extensions-api#48]
Below is the proposal for versioning. Please leave feedback.

- Require semver (e.g. 1.3.2) in the extension manifest
- Users will see different major versions of extensions in Tableau Desktop. However, only the latest minor version will show up
- Because extensions are web apps, most changes will occur in the web app, not the manifest
- Requests to your server will include a header with:

1. API version
2. Tableau version
3. Extension version

**Comment by LGraber** [comment]
Closing this as we are tracking versioninig related items elsewhere
