### ISSUE TITLE
Transparency for non sandboxed extensions

### ISSUE THREAD

**Issue by Dhruvjain07** [tableau/extensions-api#481]
Hi there. Transparency is available for Sandboxed extensions, but not for non-Sandboxed ones. I'm working on an extension from scratch but it needs to connect to an external web client, therefore I cannot make it as a Sandboxed one. I would like it if there is a way to have transparent background on dashboards available for non-Sandboxed extensions too.
Thanks

**Comment by johnDance** [comment]
Hi @Dhruvjain07 
Unofficially, the sandbox requirement only applies to extensions running on desktop. Does that make a difference for you? The investigation for how to officially support transparency in network-enabled extensions is on our backlog, but below a few other items right now.
John

**Comment by Dhruvjain07** [comment]
Hi @johnDance
PS: I'm new to Tableau
I did not understand "extensions running on desktop". Do you mean if I visualize the dashboard from the server, I will see the transparency effect?
Thanks

**Comment by johnDance** [comment]
Hi @Dhruvjain07 
There are several ways to use Tableau. 
1. We have a Windows & Macintosh version that you can download (https://www.tableau.com/products/desktop/download). We refer to both of these as "desktop".
2. We have a version that runs in your browser. We normally refer to this as "running on server".
So yes, if you visualize the dashboard in your browser, you will see any transparency that you use in your document.
John

**Comment by Dhruvjain07** [comment]
Thanks for the clarification @johnDance. It helps.
