### ISSUE TITLE
Kepler.gl Extension breaks in 2021.1+ versions of Tableau

### ISSUE THREAD

**Issue by demartsc** [tableau/extensions-api#487]
**Describe the issue**
As described here: https://github.com/keplergl/kepler.gl-tableau/issues/39 if we try to use kepler.gl extension in 2020.4 it works, but in 2021.1+ it no longer works. I am thinking that it could be related to the lack of WebGL support in Tableau Desktop on Mac. 

**Version information:**
 - Tableau version: 2021.1+ Desktop
 - OS: Big Sur
 - Browser: Chrome

**Steps to reproduce (please include a code snippet, if possible):**
1. Create a dashboard
2. Add a sheet with some geo data
3. Drop an extension, add Kepler from gallery
4. You will note that the base map doesn't render. 

Map should render/work as it did in 2020.4 and below.

**Comment by elbandito** [comment]
@demartsc this maybe related to #378

**Comment by johnDance** [comment]
Hi @demartsc 
I'm afraid WebGL support has been a trail of tears.
@elbandito is correct. This is the same issue as #378. There continue to be incompatibilities between WebGL and our general rendering engine. In 2022.2, WebGL for Macintosh can be enabled using: open -a Tableau.app --args -DUseSoftwareRenderingForWebViews=false, although the user could run into rendering issues. Yes, I know... this is not what you want to hear. But this was the best we could do. Meanwhile, WebGL works as expected on server. As we move to a different rendering model, I'm hoping that this can improve in the future. Meanwhile, the tears continue...
John

**Comment by demartsc** [comment]
Darn such a bummer. I will update support on the kepler.gl extension docs to only include server for the time being I guess. I will close this now and if anything changes definitely let us know. Thanks!
