### ISSUE TITLE
Can't start extension after adding a table

### ISSUE THREAD

**Issue by ihrimech** [tableau/extensions-api#493]
I developed an extension that is working perfectly fine. But once I add a second/third table, I get the same error when loading the extension. Even just putting a simple **.trex** file with just `tableau.extensions.initializeAsync()` doesn't work ...

And more precisely in this part of the code : 
![image](https://user-images.githubusercontent.com/9653433/167862871-0196eb6c-a5b4-47d5-9074-b05898797104.png)

... seems to timeout into this error : 
![image](https://user-images.githubusercontent.com/9653433/167863562-449d3757-d346-42dd-9d14-1011f03744b9.png)

**Version information:**
 - Tableau version: 2022.1
 - OS: macOS Monterey 12.3.1
 - Browser : **Tableau Desktop**
 - Version : 
<img width="248" alt="image" src="https://user-images.githubusercontent.com/9653433/167863835-0ccc82fb-849a-4af8-aa33-7525df37d40e.png">

Please help ...

**Comment by johnDance** [comment]
@ihrimech - Could you share your workbook with us? Also, what version of extensions are you using?
Thank you!
John

**Comment by ihrimech** [comment]
Hello @johnDance,

I'm currently using version 1.8.1 of the extension-api.
Is there a way to privately and safely communicate the workbook ?

Thanks for taking the time for this issue.

**Comment by johnDance** [comment]
@ihrimech - We can't accept any confidential data. Would it be possible to create a filtered extract and then send a very minimal workbook to us? See https://help.tableau.com/current/pro/desktop/en-us/extracting_data.htm

John
