### ISSUE TITLE
Proposal: Access Tableau Server Logged in User data with the Extension API

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#50]
It would be great to be able to access Logged In user data to make the extension more flexible. 
It would things possible like logging, row level security and user specific information in the Extension.

**Comment by sharif-zakhary** [comment]
This is exactly what we are hoping to accomplish with extensions as well.      I'm making the assumption that the extension page will be able to identify user credentials just like any other intranet page we build currently, but having access to Tableau User details would be an added bonus.

**Comment by johnDance** [comment]
We are looking into a unique user "hash", but accessing logged in user is prohibited by our security team.
