### ISSUE TITLE
Bug: Debugging console stops working when you reload Extension in dashboard

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#51]
Right now when you reload the extension in your dashboard the debugging console on port 8696 stops working and you have to start it up again.

Would really help if that can be fixed, so we can debug our extensions faster.

**Comment by andre347** [comment]
You can pause the extension on the dashboard. Then reload, but I agree, this should be easier and faster.

**Comment by johnDance** [comment]
This was fixed back in 2020. :-) 
...but we never updated the issue. :-(
