### ISSUE TITLE
The extension javascript files contain sourceMappingURL, but not the actual map files.

### ISSUE THREAD

**Issue by koesper** [tableau/extensions-api#512]
The actual extension .min.js files contain a link to the map file, but the actual map files are not bundled
This makes debugging a bit trickier, and gives useless 404 errors.

**example**
the latest file [lib/tableau.extensions.1.latest.min.js](https://github.com/tableau/extensions-api/blob/main/lib/tableau.extensions.1.latest.min.js#L2) contains this line:
`//# sourceMappingURL=tableau.extensions.1.9.0-pre.56.min.js.map`

That implies that that file should be in the same folder, but unfortunately this doesnt exist.
I've found that reference all the way back up to version [1.4.0](https://github.com/tableau/extensions-api/blob/main/lib/previous/tableau.extensions.1.4.0.min.js)

Please either remove that line, to remove the reference.
or add the actual map files (please doublecheck path then, the `-pre.56` might not be needed)

**Comment by johnDance** [comment]
Thank you @koesper 
We will get this fixed for the next release.
John

**Comment by koesper** [comment]
@johnDance slightly offtopic, but same issue. I also see this happening in the Embedding API
https://MYTABLEAUSERVER/javascripts/api/tableau.embedding.3.0.0.min.js
has a reference to `//# sourceMappingURL=tableau.embedding.3.0.0-alpha.71.min.js.map`, which doesnt exist.
Might already be fixed, since we are running a slightly old version (2021.4.12)

**Comment by johnDance** [comment]
Thanks. I'll alert the embedding team also.
John

**Comment by koesper** [comment]
Still there in v1.10.0 unfortunately
https://github.com/tableau/extensions-api/blob/main/lib/tableau.extensions.1.latest.min.js#L2

**Comment by johnDance** [comment]
Yes, it is there. But the map file is now included in the release to aid in debugging needs.

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/37640168/209844407-7f23ad0d-7fea-4d0a-b84e-c8bf2e544a6c.png">

**Comment by koesper** [comment]
Thanks @johnDance, i had expected the map file to have the same name, but this should work as well. Thanks and happy new year!
