### ISSUE TITLE
Question / Possible Issue: Working with Azure App Service deployment is non-responsive

### ISSUE THREAD

**Issue by AlexWareUltromics** [tableau/extensions-api#518]
Hi

Is there anything in particular that's needed to set this up on Azure app services? I've deployed it to an Azure Windows app service (Node 18 LTS as the runtime stack) and when I try to use the Tutorial 6 extension (selecting a sheet and then sheet marks), it does nothing. Clicking the wrench is completely non-responsive, not even an error message. The tutorials only mention using localhost which isn't useful in a production environment.

Is there something I'm missing here?

Thank you.

**Comment by AlexWareUltromics** [comment]
Update to this, the code repo looks for the /lib/ directory which weirdly isn't available when the app is deployed to an Azure app service. I made a copy of that folder and its scripts called /libx/ and altered the extension library address in the html to match (/libx/tableau.extensions.1.latest.js) and this has resolved the issue it seems.

**Comment by johnDance** [comment]
Glad you found the issue. You are correct that localhost doesn't help for production environments. That is meant for local development and testing.

Welcome to the Extensions API! 

John
