### ISSUE TITLE
BUG: Extensions disappears when exporting to image or PDF

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#52]
We are currently creating some additional Viz types with the Extensions API.
Really fun and it opens a tons of possibilities!

But when I tried to export my dashboard to PNG to show off my new Viz type it didnt render the Extension. I know this is the same for webpage parts but it would be create if the extensions can be exported in a image / PDF as an snapshot image for example.

**Comment by tfoldi** [comment]
This is due to the same security constrain as for HTML frames in dashboards. Extensions cannot be securely exported (at least now) since it would require the server to execute the code (while now your browser executes it).

**Comment by johnDance** [comment]
Moving all discussion to https://github.com/tableau/extensions-api/issues/309.
