### ISSUE TITLE
Extension api breaks when there is no data in sheet, Issue related to DataTableReader

### ISSUE THREAD

**Issue by IamMiruto** [tableau/extensions-api#525]
This issue occurs when the extension is trying to get data from the sheet with the new pagination option (dataTableReader) and the sheet is empty. This not only breaks the extension but the tableau extension API itself, so even if I try to load a new extension / restart the current one, the extension API does not respond. 

When I tried the same in Tableau online, there was an error message in the console. 

![Screenshot 2023-05-03 at 16 31 54](https://user-images.githubusercontent.com/96570758/235952192-cd78c17f-aef2-48ec-9924-5d0cf9e6ef10.png)

However in tableau online the issue gets resolved on reload. 

 - Tableau version: 2023.1 (Desktop)
 - OS: macOS

**Steps to reproduce:**

https://user-images.githubusercontent.com/96570758/235952145-2a660cd2-e172-4c1f-85b0-5dde87daab46.mov
1: Load and configure the extension with paginated data fetching (DataTableReader). 
2: Apply a filter which removes all data from the datasheet. 
3:  Reload the extension to trigger data fetching. 

What do we expect : 

What we expect is an empty object as a return, or an option in the API to query and check if there is any data available in the sheet before fetching the data. 

Here is a demo workbook with the above-mentioned issue. 

[APIIssue.zip](https://github.com/tableau/extensions-api/files/11384026/APIIssue.zip)

**Comment by merlijnbuit** [comment]
Any update here please?

This issue is crashing many customer dashboards.

**Comment by uidev15** [comment]
Any updates on this please?

I recently came across this error

![image](https://github.com/tableau/extensions-api/assets/47506614/1aaed6ce-470a-49b4-9293-3c260860e967)

This is the javaScript code

// Use `await` only inside an `async` method

let vizActiveSheet = viz.workbook.activeSheet;
if (vizActiveSheet.sheetType === "worksheet") {
  const dataTableReader = await vizActiveSheet.getSummaryDataReaderAsync();  **_---> It breaks from this line when no data in sheet_**
  const dataTable = await dataTableReader.getAllPagesAsync();
  await dataTableReader.releaseAsync();
  // ... process data table ...
}

**Comment by bcantoni** [comment]
Update: We have a team internally working on this issue now, so standby for further updates as we make progress on a fix.

**Comment by bcantoni** [comment]
Update: this bug has been fixed and it should be included in the next release (date TBD).

**Comment by johnnyb25us** [comment]
Hello.  I see the status of this is still open and 2023.3 was released in October.  Does this mean that this fix was not included in 2023.3?  Will this definitely be in the first 2024 release?  Regards.

**Comment by jbrant** [comment]
Has a date for the release that includes this bug fix yet been determined yet?

**Comment by bcantoni** [comment]
Thanks all for your patience on this one. This is fixed in 2024.1 which is currently being rolled out across Tableau Cloud.
