### ISSUE TITLE
Datasource getActiveTablesAsync Method triggers an internal error

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#62]
I used tableau log viewer to collect some of the log data:
![stacktrace](https://user-images.githubusercontent.com/5736783/33487509-c07647c8-d6ad-11e7-8d9e-b6d8e9f2c906.png)

**Comment by lbrendanl** [comment]
Thanks for reporting @tjallingt, may I ask what underlying datasources you were connected to?

**Comment by tjallingt** [comment]
Oh I'm sorry i forgot to mention, this extension is running inside the superstore dashboard that is included in the tableau desktop installation

**Comment by Kovner** [comment]
Thanks Tjalling. I've logged this internally and will have someone on the team investigate.
