### ISSUE TITLE
Proposal:  Server visibility into extensions usage

### ISSUE THREAD

**Issue by benlower** [tableau/extensions-api#65]
- When publishing workbooks that contain Extensions, Tableau Server will 'register' those extensions to the Server repository.
- There will be a new Server Admin View containing information about which Extensions are in use, which views/workbooks they are attached to, and how often they are loaded.
- There will be a new tab in the Content->Workbook page that lists metadata about the Extension: Name of Extension, Extension Version, Author's Name, Author's Email address, Author's website, whitelist status.

**Comment by LGraber** [comment]
We are currently tracking all of this information. We have not determined exactly how to expose it all.
