### ISSUE TITLE
Extensions are not getting recognised in Tableau Desktop 10.5.0 Beta macOS

### ISSUE THREAD

**Issue by phatak-dev** [tableau/extensions-api#69]
Hi,
I have installed Tableau Desktop 10.5.0 Beta 2 on macOS. I have copied sample Datasource extension to extension folder. It's not showing up in the UI. I see below errors in log

```
{"ts":"2017-12-21T15:17:34.525","pid":48834,"tid":"b9cbb5","sev":"error","req":"-","sess":"-","site":"{50E95D04-58BD-4A68-9790-54C401A2DCFB}","user":"-","k":"msg","v":"AddIn Registration in File 'DataSources.trex': 'Error(2,89): no declaration found for element 'manifest' (id: /Users/madhu/Documents/My Tableau Repository (Beta)/Extensions/DataSources.trex)'"}
```

**Comment by phatak-dev** [comment]
@lbrendanl any pointers u can give?

**Comment by Kovner** [comment]
@phatak-dev 10.5.0 Beta does not have Extensions functionality. You need to be on the Developer Preview Alpha build. Do you have access to that project in prerelease.tableau.com?

**Comment by phatak-dev** [comment]
I don't see any such release on that site. Do I need to signup specifically for that? Or can you provide direct link to same? Thank you.

**Comment by Kovner** [comment]
@phatak-dev Yes, you have to sign up for the developer preview:
https://prerelease.tableau.com/key/EXTENS10NSAP1

**Comment by phatak-dev** [comment]
@Kovner it's working now. Thanks a lot.
