### ISSUE TITLE
Ability to connect to the underneath source directly

### ISSUE THREAD

**Issue by phatak-dev** [tableau/extensions-api#71]
Hi,
Current *ConnectionSummary* interface doesn't expose connection details of underneath source. If we want to access raw data only option is to use * getUnderlyingDataAsync* which may be too much load on node.js server memory. Is there any plans to add ability to pull data directly from the source?

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
