### ISSUE TITLE
Publishing Extensions to the Extensions Server

### ISSUE THREAD

**Issue by andre347** [tableau/extensions-api#75]
I'm trying to view dashboards that contain extensions on the server client that I installed. I'm getting an error message and if I look at the traffic I get an internal server error (500). It looks like I'm missing a JS package (hide-load-indicators.js). 

![screen shot 2018-01-22 at 14 10 49](https://user-images.githubusercontent.com/22317522/35233156-3189e89c-ff95-11e7-900a-6ee56f306393.png)

This is the server version I'm using:
![screen shot 2018-01-22 at 16 57 02](https://user-images.githubusercontent.com/22317522/35233195-4eed4dc0-ff95-11e7-87f7-7de036239a6b.png)

**Comment by KeshiaRose** [comment]
Assuming this has been fixed since release, please re-open if that's not the case.
