### ISSUE TITLE
Unable to listen for KeyDown event on "T" key

### ISSUE THREAD

**Issue by ns-tjlewis** [tableau/extensions-api#76]
While editing a dashboard on desktop, the "T" key seems to be overridden to toggle between Dashboard and Layout menus. Within my extension, I have a text input that currently ignores the "T" key; it'd be great if this hotkey was disabled while the user is interacting with an Extension.

Is this a known issue? Thanks.

**Comment by andre347** [comment]
Yes, I have the same issue. Letter T is a hotkey to switch between formatting panes on the dashboard. I also raised this on the Pre-release site.

**Comment by Kovner** [comment]
Thanks all, we know of this issue and have a plan to fix it. We don't yet know which alpha release it will be a part of, though.

**Comment by KeshiaRose** [comment]
Fixed in 2018.2.
