### ISSUE TITLE
Bug with Tutorial and tableau-extensions-0.8.0.js

### ISSUE THREAD

**Issue by frederiw** [tableau/extensions-api#78]
Hi, I'm attempting to learn how to write extensions and downloaded all the files, etc today.  I got error messages from tutorial Part_1 onwards in tableau after adding the extension to a dashboard in tableau.  When I changed tableau-extensions-0.8.0 to tableau-extensions-0.7.0 in the MarksSelection.html of each part, the error didn't appear and things started working in tableau.  Anyway, I'm new to all this so debug is above my head, but letting yall know.  Or maybe its an issue with my setup.  Also, thanks for the tutorials, i hope to find the functionality i need in one of them and hack together the solution i need! -Fred

**Comment by d45** [comment]
Hi Fred,
Thanks for your interest in extensions. Sorry to hear that you were having trouble getting the tutorial to work. I am glad you were able to figure out a solution. 

It looks like you ran into a compatibility problem with the version of Tableau you were using and the version of the Tableau extensions JavaScript library that tutorial was referencing.  It gets kind of tricky. You are not alone. To help with the potential version mismatch problems, we just added a matrix that shows the compatibility, see [Known Issues](https://prerelease.tableau.com/project/article/default.html?cap=52e2710a0793434d82142736c7ab3029&arttypeid=f592dc03830d480a862740e4a6bde998) on the Extension API Developer Preview site. 

At every release of the Developer Preview we introduce new features, so to get the best experience, you need to download the latest version of Tableau and the latest version of the JavaScript library from the [Extensions API Developer Preview](https://prerelease.tableau.com/) site. The tutorial and samples are updated at each release to point to the latest extensions JavaScript library.  



Hope this helps. 
Dave

**Comment by KeshiaRose** [comment]
Assuming this has been fixed as of official release but please re-open if you are still seeing the issue with marks selection.
