### ISSUE TITLE
Latest version of extensions always gives error

### ISSUE THREAD

**Issue by cyclomarc** [tableau/extensions-api#86]
Have installed latest version of Tableau desktop (tableau-setup-std-main.18.0208.2310-x64).

Have also installed the latest extensions-api-master (the one including UI Namespace example)

Open Tableau desktop and connect to datasource "superstore"; you get immediately an error: Internal Error - An unexpected error occurred and the operation could not be completed.

Any idea whats going wrong ?
![afbeelding](https://user-images.githubusercontent.com/5204113/36356148-e33430c6-14ed-11e8-8285-8b016662cdc9.png)

**Comment by cyclomarc** [comment]
Looks like the error is related to the datasources.  As soon as you click in this release on a datasource, the error is shown.  Can I lookup more info about the error in an error log or so ?
thx
Marc

**Comment by cyclomarc** [comment]
This is the log file, but no indication of an error.
[log.txt](https://github.com/tableau/extensions-api/files/1735061/log.txt)

**Comment by andre347** [comment]
Same issue here.

**Comment by cyclomarc** [comment]
Problem solved for now, but very strange behavior.  I opened Tableau desktop and instead of trying to connect to a datasource, click on "open sample workbook - superstore".  This opens without problem.  Then close and reopen Tableau and try to connect to a datasource (eg excel or so).  In my case this then worked ...  and the error is no longer shown.

**Comment by Kovner** [comment]
We believe this will be fixed in the Developer Preview build that will be released next Wednesday.
