### ISSUE TITLE
Scrolling awkwardness on OS X with Tutorial extension

### ISSUE THREAD

**Issue by elatt** [tableau/extensions-api#91]
When trying to display many selected marks in the sample Tutorial Complete extension, the scroll behavior is very awkward on my Mac (10.12.6). I prefer having my scroll direction on my trackpad to have Natural **unchecked**. With the scroll settings as such, when I try to scroll inside the datatable that lists all the selected marks (especially when trying to scroll horizontally), it behaves as if it is confused which way I am trying to scroll the contents. If I set my OS settings to have a _Natural_ scroll direction then things do behave more sanely.

**Comment by Kovner** [comment]
So does it scroll the incorrect direction or does it do something weird like jitter back and forth?

**Comment by elatt** [comment]
It jitters back and forth.

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
