### ISSUE TITLE
falsy closeDialog payload causes internal error

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#99]
Even though payload is documented to be optional (https://tableau.github.io/extensions-api/docs/interfaces/ui.html#closedialog) if it is a falsy value (`false`, `0`, `''`or `undefined`) i get this error message:
![image](https://user-images.githubusercontent.com/5736783/38367436-f2dace4a-38e2-11e8-97f5-50ba9c7b8f44.png)

I'm aware that it is supposed to only take string arguments but even an empty string or `undefined` cause this error so it is definitely a bug somewhere.

**Comment by Kovner** [comment]
Ah good catch! I will log this internally. Thanks.
